### ISSUE TITLE
Is it possible to get this working with the multidiffusion plugin for upscaling?

### ISSUE THREAD

**Issue by adjarar** [hako-mikan/sd-webui-regional-prompter#100]
I've been experimenting with upscaling with this plugin https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111 and the results have been mixed. The biggest issue is that to upscale the image and add details, you need a relatively high noise strength of about >= .6. However, depending on the prompt this usually adds unwanted artifacts to the image like people who aren't supposed to be there. Ideally, you would mask each section off and add a custom prompt for each mask. Combining these two plugins seems like a good idea, but I don't know how feasible it is to make these two work together. Any thoughts on this?

**Comment by Symbiomatrix** [comment]
"Combining" is not "working with".
Look at the number of issues on that extension, open and closed. Estimate x3 that number. Assume a dev far less skillful than pkuliyi (& kahsolt), with regards to myself at least.
I would say, probably not.

**Comment by adjarar** [comment]
Are you saying it's too much work, or it's simply not possible? I'd try it myself, but I have insufficient knowledge of stable diffusion right now to attempt this.

**Comment by Symbiomatrix** [comment]
I think I don't understand what's bothering you in multidiffusion, or how regional's method is supposed to remedy that. Multidiffusion does have a regional prompt control. It appears to be perfectly functional. From what I gather in the dev explanation and paper, it creates multiple base noise tiles, and conditions each gradually according to its own prompts whilst merging in a weighted fashion, per step, attempting to adhere to the expected model's output. That's about as close to masking each section off as can be (provided there's no overlap).

**Comment by Symbiomatrix** [comment]
Alright. Good luck.
