### ISSUE TITLE
[bug] Divide mode Prompt: Using lora doesn't work as intended

### ISSUE THREAD

**Issue by flyfront** [hako-mikan/sd-webui-regional-prompter#101]
# Steps to reproduce
two problems with lora. I suspect something is wrong with this extension parsing prompts containing lora.

## Use lora in the middle of the prompt, the region range is strange

In the prompt example, 3 areas are specified, but the result is that only 2 areas are applied, and the apron area is not the intended extent.Using lora at the end of the prompt, it will work as intended.

example
```
(masterpiece, best quality, absurdres:1.3), sfw,
<lora:flat2:-1>
indoors, messy bed room, (zantangle, zantangle:1.3),
pale pink nurse (1girl solo:1.3) lying side on sheets, (cowboy shot:1.3), eyewear (smile:1.1) face focus,
white long apron and skirt, (very long brown hair spread out disheveled:1.3) blunt bangs,
simple nurse cap, pantyhose, breasts, cusion pillow BREAK
(frilled embroidered:1.1) (floral print:1.5) apron with safety pin, apron BREAK
(white:1.3) pantyhose, pantyhose BREAK
(eyewear:1.5), eyewear

Steps: 25, Sampler: DPM++ 2M Karras, CFG scale: 10, Seed: 4079728831, Size: 1024x576, Model hash: 19151bff86, Model: breakdomain_M2000, Clip skip: 2, RP Active: True, RP Divide mode: Prompt, RP Calc Mode: Attention, RP Ratios: "1,1", RP Base Ratios: 0.2, RP Use Base: False, RP Use Common: False, RP Use Ncommon: False, RP Change AND: False, RP LoRA Neg Te Ratios: 0, RP LoRA Neg U Ratios: 0, RP threshold: "0.6,0.7"
```

Reference: See my twitter post. 
https://twitter.com/flyfront/status/1655921163690975232

## Doesn't work with multiple lora
Put two or more lora designations other than the end of the prompt, it seems that Regional Prompter is not working

If the prompt mode worked, the mask image of the region should appear with the generated image, but it doesn't.
Using lora at the end of the prompt, it will work as intended.

example
```
(masterpiece, best quality, absurdres:1.3), sfw,
<lora:flat2:-0.7>  <lora:anime_minimalist_v1-000020:-0.3> anime minimalist <lora:lit:0.2>
indoors, messy bed room, (zantangle, zantangle:1.3),
pale pink nurse (1girl solo:1.3) lying side on sheets, (cowboy shot:1.3), eyewear (smile:1.1) face focus,
white long apron and skirt, (very long brown hair spread out disheveled:1.3) blunt bangs,
simple nurse cap, pantyhose, breasts, cusion pillow BREAK
(frilled embroidered:1.1) (floral print:1.5) apron with safety pin, apron BREAK
(white:1.3) pantyhose, pantyhose BREAK
(eyewear:1.5), eyewear
```

# environment
- WIndows10 Pro
- GeForce RTX3060 12G
- python: 3.10.7
- torch: 2.0.0+cu118
- xformers: 0.0.17
- gradio: 3.28.1
- commit: [5ab7f213]
- checkpoint: [19151bff86]

## related extensions
sd-webui-regional-prompter [ a5fd8533 (Sun May 7 09:00:58 2023)]
sd-webui-lora-block-weight 11f1d4d2 (Mon May 8 10:02:19 2023)
a1111-sd-webui-locon 04b768ba (Fri Apr 14 17:00:50 2023)

**Comment by Symbiomatrix** [comment]
Presence of lora seems to throw off the tokenizer at `ptokens, tokensnum = shared.sd_model.cond_stage_model.tokenize_line(ppl[0])` and probably in the subsections too; judging by the tokens, it would appear that the lora name itself is getting tokenised (shorter lora names get less tokens); this causes the chunked tokens to overflow (>75 tokens, so `ptokens[1].tokens` is a thing; before you were at 71), and thus your pantyhose keyword is not found, being near the end.
I see two likely problems:
1) Tokenising lora names would be an error, in the regular tokenisation process lora would likely be filtered out.
2) In case main prompt is >75 tokens, the keyword should be searched in each section, and the index be updated accordingly (ie +75*section). I'm not sure whether this will incur additional issues down the line, where .pe is used.

**Comment by flyfront** [comment]
Thank you for Symbiomatrix.

I see, the token calculation was shifted by the amount of using lora.
As a result, the token in the BREAK area at the end of the prompt was misaligned, and the region division was not performed properly.
I understand that the two phenomena that occurred in my environment are caused by that problem.

I look forward to merging the fix pull request.

**Comment by Symbiomatrix** [comment]
@flyfront No problem. Did you test it? As far as I can tell it makes the results identical, but I've no idea whether they're up to par since I haven't gotten around to experimenting with prompt mode yet.

**Comment by flyfront** [comment]
@Symbiomatrix It works correctly!
The extension recognizes regions correctly when using the "Symbiomatrix:Prompt1" branch.

prompt:
```
(masterpiece, best quality, absurdres:1.3), sfw,
indoors, messy bed room, (zantangle, zantangle:1.3),
<lora:flat2:-0.7>  <lora:anime_minimalist_v1-000020:-0.3> anime minimalist <lora:lit:0.3>
pale pink nurse (1girl solo:1.3) lying side on sheets, (cowboy shot:1.3), eyewear (smile:1.1) face focus,
white long apron and skirt, (very long brown hair spread out disheveled:1.3) blunt bangs,
simple nurse cap, pantyhose, breasts, cusion pillow BREAK
(frilled embroidered:1.1) (floral print:1.5) apron with safety pin, apron BREAK
(white:1.3) pantyhose, pantyhose BREAK
(eyewear:1.5), eyewear
```

Forgive me for not drawing glasses.
![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/599976/187e3a59-66c3-4b6c-a881-8818aacce1ab)
![00034-2699582597](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/599976/66e0c1fa-19d3-4647-ab80-015d1e81d17c)

**Comment by Symbiomatrix** [comment]
Awesome, nicely done.

**Comment by flyfront** [comment]
PR is merged.

The problem is solved, can I close it?

**Comment by Symbiomatrix** [comment]
Sure, dude. It's your issue.
By the way, noticed you had a small typo in the prompt - it's "cushion". Probably the difference is small in the embedding.

**Comment by flyfront** [comment]
oh cusion/cushion! thx.
I close it.
