### ISSUE TITLE
pixelated output + washed out colors when using 2 loras with a sampler that is not DPM++ 2M Karras

### ISSUE THREAD

**Issue by pham-nhat-khanh** [hako-mikan/sd-webui-regional-prompter#103]
( sorry big file )
![xyz_grid-0010-3357413711](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/24745349/bf22078c-7da4-4a8c-b1a4-dd85cd731dd4)
![Untitled](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/24745349/3a71a6cf-53c6-4714-ac2b-2f515d1b14f5)
is this behaviour expected? should i just stick with DPM++ 2M Karras + cfg scale 7? does this have anything todo with the loras I'm using?

**Comment by Symbiomatrix** [comment]
See #42 , and I think https://github.com/opparco/stable-diffusion-webui-two-shot/issues/29.
It is known, would be loath to call it expected but no solution has been reached. Lowering cfg + increasing steps help, and there's the unet + text weights which basically control how badly some loras are corrupted at the cost of possibly corrupting other regions (needs to be upgraded).
Yes, it varies by specific loras as illustrated yonder, and possibly combinations.

**Comment by pham-nhat-khanh** [comment]
thanks! I'll experiment with different parameters + inpainting then. Closing the issue.
