### ISSUE TITLE
Support for tiling/upscaling?

### ISSUE THREAD

**Issue by adalast** [hako-mikan/sd-webui-regional-prompter#104]
I'm trying to upscale an image I made with the regional prompter.  It would definitely still benefit from being able to maintain the regional definitions based on the input image proportions, so the tiles that are being processed have the correct prompts and proportions on the regional splits that they would have in the original image.  I would think that it shouldn't be too hard to at least figure out what the region splits for the tiles should be as the system stores the tile size and center pixel coordinates, and from there it is some LERPs away from solving the tile splits.  The only thing that I could see being an issue would be trimming the prompt so it was structured properly for the new split ratios.

Also, I know it doesn't currently work because I am getting intrusion of one particular keyword that is supposed to be in a single panel of the image into all of the others and it is really apparent.  There is a prompt for images 2 and 3 for the 3rd panel have "smoke" included, and you can see that it is pervading the upscales for all panels.
![00059-2199984597](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/452159/2b1bfc27-7cfe-411c-9c22-5e5f99762031)
![00015-3685815142](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/452159/0a6c85da-bc93-44cd-99ca-e95d9acd2f0b)
![00003-4138172259](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/452159/158b95c8-7389-44fb-b3cc-8f94056e03b5)

**Comment by hako-mikan** [comment]
Are you still having this problem?
It is recommended to use the Latent mode since this erosion is stronger in the Attention mode.
