### ISSUE TITLE
Negative Prompting for regions

### ISSUE THREAD

**Issue by a3nima** [hako-mikan/sd-webui-regional-prompter#105]
Hi. Thanks everybody involved for this great extension! 
I want to use a negative prompt for one certain region.
I checked Common Negative Prompt and after the common prompt text I wrote: "BREAK BREAK BREAK _negative prompt-text for Region 3_." Then I got an error message.
How do I set a common negative prompt and then a negative prompt for one specific region? 
Thank you very much :)

**Comment by Symbiomatrix** [comment]
Basically looks correct. Did you also structure the positive in the same manner? Need to see the exact settings you've used and full error log to estimate cause.
Hako recently merged the 1d & 2d mode, I spotted some areas which need improvement, you could try the 2d syntax:
common ADDCOMM 1 ADDROW 2 ADDROW 3
Or ADDCOL if that's the direction. No need to set the checkbox.

**Comment by a3nima** [comment]
Hi. Thanks for the reply. Today I ve tried it again. And I did not get an error. Also: It worked :) Thanks
