### ISSUE TITLE
Can the drawn mask be saved and reused?

### ISSUE THREAD

**Issue by ImpossibleAd436** [hako-mikan/sd-webui-regional-prompter#106]
Is there any way to save all the mask information to reuse again later?

**Comment by Symbiomatrix** [comment]
Working on it. Prototype: https://github.com/Symbiomatrix/gradio-test-polygon
Unfortunately, gradio has been less than compliant (https://github.com/gradio-app/gradio/issues/4088), and I have more pressing matters.
Plan is to support upload from a slightly deteriorated mask image, and save / load from presets, with the mask image stored separately so it's more modular.

**Comment by ImpossibleAd436** [comment]
> Working on it. Prototype: https://github.com/Symbiomatrix/gradio-test-polygon Unfortunately, gradio has been less than compliant ([gradio-app/gradio#4088](https://github.com/gradio-app/gradio/issues/4088)), and I have more pressing matters. Plan is to support upload from a slightly deteriorated mask image, and save / load from presets, with the mask stored as a png separately so it's more modular. I'd also like to support background images so the user can trace their regions according to eg a depthmap or openpose mask they'd upload (a trick noted elsewhere), rather than merely wipe them as the prototype does currently, but I'm ambivalent on how to prevent "my mask wasn't detected because its colour was slightly off" type complaints, Perhaps I should automatically display the background mask so it clearly shows which parts are valid.

Thanks for the reply!

Being able to reuse a mask in an easy way would be really really helpful. Once a new mask is generated, or a new instance of SD is run, there is basically no way to recreate a previous image, from seed/settings, because precisely recreating a mask manually is basically impossible, and I assume that any variation to the mask will change the image. Being able to save "mask presets" would be even better.

Thanks for this extension by the way, it's incredibly useful!

**Comment by Symbiomatrix** [comment]
I haven't tested, but you're probably right about the irreproducibility. The pixel variation would be compounded over the unet layers, the compressed dimensions and across steps.
Anyway, in case you were unaware, the version is up already.

**Comment by ImpossibleAd436** [comment]
> I haven't tested, but you're probably right about the irreproducibility. The pixel variation would be compounded over the unet layers, the compressed dimensions and across steps. Anyway, in case you were unaware, the version is up already. Credit's to hako, but you're welcome.

That's great news thanks, I will give it a try!

Yeah I was wondering about reproducibility, i.e. does the masked space remain consistent (in terms of noise inference) over multiple generations? I would assume so, but I guess maybe there might be variation even with the same seed and settings? I'm honestly not technically compentent enough to know the answer to that, but I'll give it a try.

Either way, sometimes I make a mask which produces the kind of results I am looking for and it will be great to be able to reuse that exact mask again later.

Thanks again.

**Comment by Symbiomatrix** [comment]
With the exact same mask, as is exported by save_preset, results should be consistent; there's a small list of seed breakers in general (https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Seed-breaking-changes), but the mask was constructed in such a manner that colours correspond exactly to the region numbers. Within the regional forward process, the initial mask is simply scaled down via torchvision.transforms' resize method which is perfectly deterministic as well. The rest of the process is basically the same as regular generation, except for being repeated per region.
