### ISSUE TITLE
[Suggestion] Add IDs for important parts of the extension

### ISSUE THREAD

**Issue by daswer123** [hako-mikan/sd-webui-regional-prompter#113]
Hi, I am developing the canvas-zoom extension and wanted to add itegration with your extension, but there was some problem.

Look, you don't have special element IDs in your tabs, which makes it impossible to hang events through javascript.

I suggest you to add id for important parts of the extension in your code

Regional-prompter  
![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/22278673/9113df69-f23a-46fc-ade4-023f045d6f14)

Here is an example of how it is done in controlNet
![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/22278673/e21549d7-d54a-4dda-8513-855106212ce7)

**Comment by Symbiomatrix** [comment]
Hello danil.
Shouldn't be a problem adding elem_ids. Which components exactly do you want ids for, besides the main accordion?

**Comment by daswer123** [comment]
To be honest, I'm not very good at python.

In fact, there is already an id on the mask, so I think that only the id on the main element is enough for now.
![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/22278673/3e945282-5f2a-4dd0-9495-82c1a8e69cf9)

**Comment by Symbiomatrix** [comment]
And I'm almost completely clueless in frontend, but it's very easy in gradio. : )
The interface is built within script.ui, by adding layout components such as gr.Row, .Column and other blocks subclasses, and within them controls such as checkboxes, images etc. All that's needed is to add an elem_id to the specific control, like in "active" below:
![RegionalAccordion](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/41131377/2e7334c8-bee2-4f2b-a2b5-ed6d63721d58)

**Comment by daswer123** [comment]
It's easier than I thought :)
In fact, you just need to add to gr.Accordion, id and everything will be cool :)

Should I do PR or wait for an update?

**Comment by Symbiomatrix** [comment]
Yep.
Sure, send a PR if you like.

**Comment by daswer123** [comment]
Okay, soon.
