### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by RealAzmodeo** [hako-mikan/sd-webui-regional-prompter#115]
C:\Users\...\Vlad\automatic\extensions\sd-webui-regional-prompter\scripts\latent.py:140 in denoised_callback_s     │
│                                                                                                                      │
│   139 │   │   batch = self.batch_size                                                                                │
│ ❱ 140 │   │   areas = xt.shape[0] // batch -1                                                                        │
│   141                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ZeroDivisionError: integer division or modulo by zero

I get this for each step of the generation...

**Comment by Symbiomatrix** [comment]
Unless the python version you're using forgot order of operations, this could only mean that self.batch_size was initialised to 0, but not set to the correct value. The only place that happens is in right at the start of process, `self.batch_size = p.batch_size`.
What exactly did you do? Is regional enabled? Did you turn it on and then off or something?

**Comment by RealAzmodeo** [comment]
1. txt2img. It worked as intended.
2. I took the result to im2im to upscale and then switch models.
3. I ran the generation with the regional prompter ON.
4. It "worked" as it had an output image that looked right. But the log showed this for each step of the process.
5. The main issue is that after this SD doesn't seem to properly manage Vram. Before this, I was able to create bigger images, but after using Regional Prompter and getting this error I have to restart my PC.

It is important to mention I'm not a dev and I'm just a mundane user who doesn't really understand what's going on other than what I actually read.

**Comment by Symbiomatrix** [comment]
I got around to installing vlad's fork too, but I'm not really seeing any such issues with it.
It is perhaps related to some specific action, extension or hardware. Unless you can provide a simple list of actions (ie a single prompt + regions on txt, followed by what kind of upscale, and what kind of generation in step 3), I cannot determine what is the cause.
