### ISSUE TITLE
Unable to replicate quality of examples

### ISSUE THREAD

**Issue by Cruxial0** [hako-mikan/sd-webui-regional-prompter#116]
Not sure if I'm doing something wrong or not. Judging from the issues, I can't really see anyone else complaining about this.
I'm not able to reproduce the images in the README. I copied all the settings/parameters from the example prompt. I have tried across a variety of different models, settings, hires samplers, but nothing seems to do the trick.

Here is an example of what I got trying to replicate the example (this was one of the best results I got):
![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/25249091/f1089430-3686-48ab-8977-6ef601badf66)
```
(blue sky:1.2) ADDCOL
green hair twintail ADDCOL
(aquarium:1.3) ADDROW
(messy desk:1.2) ADDCOL
orange dress and sofa
Negative prompt: EasyNegativeV2
Steps: 40, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 3573226505, Size: 1056x704, Model hash: f713bab753, Model: yesmix_v15, Clip skip: 2, ENSD: 31337, Version: v1.2.0-4-g70689ecd, RP Active: True, RP Divide mode: Horizontal, RP Calc Mode: Attention, RP Ratios: "1,2,1,1;2,4,6", RP Base Ratios: , RP Use Base: False, RP Use Common: False, RP Use Ncommon: True, RP Change AND: False, RP LoRA Neg Te Ratios: 0, RP LoRA Neg U Ratios: 0, RP threshold: 0.4
```
Other times, I got results like this:
![16032-3335514042-best quality, masterpiece BREAK_(blue sky_1 2) BREAK_green hair twintail BREAK_(aquarium_1 3) BREAK_(messy desk_1 2) BREAK_orang](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/25249091/0dcb8130-667a-422f-9ca9-246b767851aa)

I'm not sure if the examples in the readme accurately represent what can be expected, and if so, that's fine. I'm just lost and wondering if I am doing something wrong. Thanks.

**Comment by Cruxial0** [comment]
Yeah okay, turning off the common negative option imrpoved it by quite a lot. This feature should be better documented. Do you happen to know what it does? I thought it was the same thing as base prompt, but for UC..

**Comment by Symbiomatrix** [comment]
https://github.com/hako-mikan/sd-webui-regional-prompter#use-common-prompt
https://github.com/hako-mikan/sd-webui-regional-prompter#difference-between-base-and-common
Same thing for positive and negative in all modes - common is copypasta.
