### ISSUE TITLE
Batch result is different using prompt mode

### ISSUE THREAD

**Issue by Lance3d** [hako-mikan/sd-webui-regional-prompter#117]
If I set batch size = 4 and using prompt mode, the result is quite different from batch size = 1. All other parameters is same except batch size.

**Comment by Lance3d** [comment]
btw, when batch size = 4 the result seems to be better

**Comment by Lance3d** [comment]
It seems to be that when batch size = 4, the effect is not applied (same result as if extension is disabled)

**Comment by Lance3d** [comment]
It seems that when batch size = 4, the effect is not applied, as if threshold = 1

**Comment by hako-mikan** [comment]
Is this issue still occurring? 
If it is, could you please provide more detailed information about the situation?

**Comment by hako-mikan** [comment]
Fixed. Thanks.
