### ISSUE TITLE
Canvas size is incorrect for wide resolutions

### ISSUE THREAD

**Issue by ImpossibleAd436** [hako-mikan/sd-webui-regional-prompter#123]
If I attempt to create a canvas, for example: 1280 x 768, the canvas isn't fully drawn. If I draw and go over the right edge, the mask is correct, in that it shows where I drew to. But the canvas is cut off so the right side of the canvas cannot be seen or drawn on accurately.

Edit: In fact the mask doesn't draw completely either. It is also limited to the drawing area of the canvas, although the actual mask resolution is correct.

**Comment by Symbiomatrix** [comment]
You're talking about the inpaint+ canvas, I presume?
The maximum canvas size is 1024x1024. How did you set it to 1280?
Seems that when the aspect ratio is roughly >1.5 (eg 1024x640), the canvas overflows to the other column; that's about the only thing I can see, and I can't do much about it since I just copied the css code from webui's inpaint, I know nothing of the language.
If you could post some screenshots, that might clarify the issue.

**Comment by ImpossibleAd436** [comment]
Ah ok, I didn't realize that.

Yes it's mainly the aspect ratio that is the issue. In terms of the masks resizing, Im not sure that I understand that. For example, if I was working with a 1.5 aspect ratio, and I wanted something on the far right, the mask that gets show below the canvas shows whatever was drawn to be about 1/3 inside the mask rather than at the edge where intended. Does the way the masks are resized at runtime resolve this? i.e. will what is on the edge in the canvas be on the edge of the mask at runtime, even though the displayed mask shows a discrepancy?

Thanks.

**Comment by Symbiomatrix** [comment]
This should clarify.
Say you started with a 256x512 mask.
![MStretch](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/41131377/87ac9238-d07f-4b5f-adc9-e9d9139c1103)

And generated a 512x512 image. Then the mask used will be variants of this (in attention the h/w are divided by 2 a few times, so actually smaller).
![MStretchB](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/41131377/8977df6f-ee19-4840-ad12-392087b8ed48)

The "mask" component will show where in the image the regions you drew are located, before resizing. Edge regions will remain on the edge.
