### ISSUE TITLE
List index out of range in mask mode

### ISSUE THREAD

**Issue by shenmxd0762** [hako-mikan/sd-webui-regional-prompter#133]
I drew region 0 to region 4 in mask mode and enabled common, base, and negative common. 
But when I used the prompts shown in the figure, it returned an error. Sometimes (just sometimes) adding two additional BREAKs at the end of the prompts can generate the image normally, but no matter what prompts are added after these two BREAKs, it has no effect on the image.
I only enabled hires and controllnet here, and no other plugins have been enabled.

![QQ截图20230526211247](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/31209203/933f521a-81fe-4bf0-8c42-00c81bcb6f0f)
![QQ截图20230526211254](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/31209203/b744d226-8735-42a2-8503-2fd6fbd2dbe6)
![QQ截图20230526211310](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/31209203/c0174ef2-7a77-4bb6-9567-e3f518aa70b7)
![QQ截图20230526211340](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/31209203/3424a751-33f4-4e37-a70d-80437a416c20)
![QQ截图20230526212859](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/31209203/1eec4b4c-c406-4c16-a9ac-2c629ad2ae50)

In addition, there seems to be an exception with the upload mask. After uploading the mask, I set the region slider to 0, and then press Draw region+show mask 5 times. I can see in the mask window that it has created the same mask as before, but no matter how many BREAKs I enter, it returned List index out of range.
I did not add any images or canvases to the drawing area above when using the upload mask.
![QQ截图20230526215724](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/31209203/666a0551-d29d-4177-8a7d-fb6717f73493)

**Comment by Symbiomatrix** [comment]
Have you saved the mask to preset, can you upload its file?

**Comment by shenmxd0762** [comment]
> Have you saved the mask to preset, can you upload its file?

![4](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/31209203/c7cd1427-628d-4528-a6dd-96e9cc50ddd8)

(masterpiece:1.3), (best quality:1.2),(2D:1.0), (anime:1.0), (illustration:1.0), (sharp:1.2), (reflection, refraction:0.8), (light rays, dappled light, light glare, lens flare:1.0), (clear, shiny:0.8), (impasto:1.1), (ultra-detailed:1.0), perspective, (underwater:1.3), scenery, ocean_bottom, air bubble ADDCOMM
scenery ADDBASE
from side, full body, floating hair, freediving, (dog_girl, anthro_female_dog:1.2), (fluffy_fur, skin_with_fluffy_fur:1.2), (full_body_fur:1.2), dog_ears, dog tail, solo, cub, (loli, petite, young_female:1.1), flat_chest, kawaii, cute, yellow fur, grey eyes, long_hair, white hair, red_bow_bikini BREAK 
(angelfish) BREAK 
(shoal of fish) BREAK 
coral, seabed, seaweed BREAK 
nothing but water

EasyNegative, (worst quality, low quality:1.3), (frame, border, film grain, greyscale:1.0), (text, signature, watermark, username:1.5), (duo, 3D, realistic, CG:1.0), (bad_perspective, bad anatomy, multiple tails), bad hands, error, missing fingers, extra digit, fewer digits, (1boy, shota:1.2), penis, extra hands, extra arms, (gloves, shoes, stockings:1.2) ADDCOMM
BREAK 
BREAK 
(coral, plants:1.1) BREAK 
text, signature, watermark, username BREAK 
(coral, plants, fish, rock:1.2) BREAK

**Comment by Symbiomatrix** [comment]
Thanks.
One more thing - did you upload through the designated upload window or directly to the inpaint+ area?

**Comment by shenmxd0762** [comment]
> Thanks. One more thing - did you upload through the designated upload component or directly to the inpaint+ area?

I uploaded it into inpaint+ area

**Comment by Symbiomatrix** [comment]
Ah, that could be one problem. Check out the [mask usage notes](https://github.com/hako-mikan/sd-webui-regional-prompter#mask-regions-aka-inpaint-experimental-function). There's a bug in gradio, couldn't make direct upload work. If you do, it won't tag your masks properly or perform necessary colour correction, so errors are quite possible.

In the original image with the water background, note that some bits of colour might be falsely detected as regions; however, if you're using the lowest regions for your main prompt, it shouldn't pose a problem.

**Comment by shenmxd0762** [comment]
> Ah, that could be one problem. Check out the [mask usage notes](https://github.com/hako-mikan/sd-webui-regional-prompter#mask-regions-aka-inpaint-experimental-function). There's a bug in gradio, couldn't make direct upload work. If you do, it won't tag your regions properly or perform necessary colour correction, so errors are quite possible.
> 
> In the original image with the water background, note that some bits of colour might be falsely detected as regions; however, if you're using the lowest regions for your main prompt, it shouldn't pose a problem.
> 
> I'll debug the prompt now.

Additionally, I seem to feel that after opening the negative common, the (gloves, shoes, stockings: 1.2) in negative prompts actually makes the characters more prone to gloves. The following image shows the effect I used (black_hand, black_feet, shoes, stockings, socks: 1.2) in negative common.
![grid-1131](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/31209203/14166c5f-9a5e-458b-bb80-d809a42c018d)

**Comment by Symbiomatrix** [comment]
Common is copypasta. All it does is prepend the text before every region. Whatever effect it has, more likely comes from the model rather than the extension. The negs on gloves & boots is way at the end of the prompt, lower weight than the whole watermark thing, so I don't think it's really being taken into account as expected.

**Comment by Symbiomatrix** [comment]
Hmm, something weird is happening with the context; just before it crashes, the size of the context jumps from 539 to 770 (ie as if from 7 regions to 10 regions).

**Comment by Symbiomatrix** [comment]
Definitely something I hadn't thought about - base is used to fill the noncoloured regions in mask mode, but what would its negative prompt be?

**Comment by Symbiomatrix** [comment]
@shenmxd0762 Alright, try this prompt, see if it crashes:
```
EasyNegative, (worst quality, low quality:1.3), (frame, border, film grain, greyscale:1.0), (text, signature, watermark, username:1.5), (duo, 3D, realistic, CG:1.0), (bad_perspective, bad anatomy, multiple tails), bad hands, error, missing fingers, extra digit, fewer digits, (1boy, shota:1.2), penis, extra hands, extra arms, (gloves, shoes, stockings:1.2) ADDCOMM
base goes here BREAK
BREAK
BREAK
(coral, plants:1.1) BREAK
text, signature, watermark, username BREAK
(coral, plants, fish, rock:1.2)
```

What's happening here is that mask mode was written with base being its own region in mind; I didn't limit it to just the positive prompt, but the negative as well (even though we haven't even added base to the negative). I could ignore base mode in negative for now, but it might be desirable to have negative base as a feature, I'm not really sure. On your end, adding one extra BREAK in neg will fill in the missing "base".

**Comment by Symbiomatrix** [comment]
Actually, scratch that... what the heck, it seems the commons are just completely omitted.

**Comment by shenmxd0762** [comment]
> @shenmxd0762 Alright, try this for the negative prompt, see if it crashes:
> 
> ```
> EasyNegative, (worst quality, low quality:1.3), (frame, border, film grain, greyscale:1.0), (text, signature, watermark, username:1.5), (duo, 3D, realistic, CG:1.0), (bad_perspective, bad anatomy, multiple tails), bad hands, error, missing fingers, extra digit, fewer digits, (1boy, shota:1.2), penis, extra hands, extra arms, (gloves, shoes, stockings:1.2) ADDCOMM
> base goes here BREAK
> BREAK
> BREAK
> (coral, plants:1.1) BREAK
> text, signature, watermark, username BREAK
> (coral, plants, fish, rock:1.2)
> ```
> 
> What's happening here is that mask mode was written with base being its own region in mind; I didn't limit it to just the positive prompt, but the negative as well (even though we haven't even added base to the negative). I could ignore base mode in negative for now, but it might be desirable to have negative base as a feature, I'm not really sure. On your end, adding one extra BREAK in neg will fill in the missing "base". I also don't think negative common currently applies to its base at all, so that might cause your gloves & boots problem - if they fall close to the base area (which theoretically has no negative), they just become scenery.

It works! In addition, after adding a line 'base goes here BREAK' in negative prompts, the (gloves, shoes, stockings: 1.2) in negative common can now function normally.

**Comment by Symbiomatrix** [comment]
@shenmxd0762 Sorry, I'll clarify, that was just a test - it's actually completely broken as far as I can tell, just wanted to make sure I'm on the right track.
I think that when you have negative common and base, it's actually turning that "all your base" clause into the common for some reason, and possibly shifting the clauses around. So for now you're probably best off not using negative common in mask mode, and instead add that base negative clause as if were a separate region when you're using it, and copypasta negs manually, till we can fix it.

The negative base thing can be easily turned off by checking `if self.usebase and pn:` everywhere in `masksepcalc`, but it's not enough - the mask still needs a neg and the prompt construction is still broken. We'll definitely have to write in better handling, but I don't have time for that at the moment.

**Comment by shenmxd0762** [comment]
> @shenmxd0762 Sorry, I'll clarify, that was just a test - it's actually completely broken as far as I can tell, just wanted to make sure I'm on the right track. I think that when you have negative common and base, it's actually turning that "all your base" clause into the common for some reason, and possibly shifting the clauses around. So for now you're probably best off not using negative common and base together in mask mode, and instead add that base negative clause as if were a separate region when you're using it, and copypasta negs manually, till we can fix it.
> 
> The negative base calculation can be easily turned off by changing to `if self.usebase and pn:` instead of just usebase everywhere in `masksepcalc`, but it's not enough - the mask still needs a neg to be applied to the base region and the prompt construction is still broken. We'll definitely have to write in better handling, but I don't have time for that at the moment.

Sorry, I didn't understand what you meant. Are you saying that I should close 'use negative common' and copy 'EasyNegative, (worst quality, low quality: 1.3),...' into each negative region?

**Comment by Symbiomatrix** [comment]
Aye. That's exactly what we did before hako added the commons. Minus the extra break at the end, that creates a redundant region. Kinda sucks, but manageable till I get around to it.

**Comment by Symbiomatrix** [comment]
I see that matrix mode suffers the same problem, so looks like it really does need to be a thing. Along with a good deal of restructuring the code.

**Comment by AIDungeonTester2** [comment]
May I weigh in on this issue? Unlike shenmxd0762, I only have a single negative prompt, but I am also encountering a list index out of range error whenever I try to generate.

Tried with both ControlNet enabled and disabled, same error.
![2023-06-03 12_49_59-Stable Diffusion — Firefox Nightly](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/130163815/388cacb2-a78a-4435-93d5-84cb367560ba)

![2023-06-03 12_50_15-Stable Diffusion — Firefox Nightly](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/130163815/5d557083-cb76-40cb-b9a1-32734c4c6fdd)

![2023-06-03 12_51_27-Stable Diffusion — Firefox Nightly](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/130163815/c8f8d31c-ba79-4ba2-97b0-46ac27bf1da9)

![poseRegionalprompterMask](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/130163815/6e755a2e-3054-4779-9d57-89db83b56f02)

**Comment by AIDungeonTester2** [comment]
Please disregard my above post, I solved the issue.

I used the wrong color values for the self-drawn mask, accidentally using HSV (0, 50, 50) for what is region 1, when that color is for Region 0 (which should be the base prompt, correct?)

I recolored the areas with Hue values of 180, 90, and 270 respectively, and it went through.

**Comment by AIDungeonTester2** [comment]
Looking at your mask, you seem to have done the same mistake I did of using the wrong HSV values for your mask.
Try changing the color of the leftmost region to 180, 50, 50, and then go 90,50,50 and 270,50,50 from left to right.
This made it work for me at least, when using common prompt and Base prompt.

It might however also have something to do with regions being in direct contact with each other, like seen in yours - when I tried it with another example, I also got list index out of range errors that I couldn't solve yet.

**Comment by shenmxd0762** [comment]
> Looking at your mask, you seem to have done the same mistake I did of using the wrong HSV values for your mask. Try changing the color of the leftmost region to 180, 50, 50, and then go 90,50,50 and 270,50,50 from left to right. This made it work for me at least, when using common prompt and Base prompt.
> 
> It might however also have something to do with regions being in direct contact with each other, like seen in yours - when I tried it with another example, I also got list index out of range errors that I couldn't solve yet.

It doesn't work, your method just changes the region used from 0, 1, 2 to 1, 2, 3

**Comment by Symbiomatrix** [comment]
@shenmxd0762 Until I've finished the negative base restructure, we cannot guarantee stability of base and common / multi negative in all cases. If a fully white background fails and image doesn't, this likely means that it's not getting enough masks for the prompts - a few specks in the background are getting interpreted as masks, and the rest are discarded. If there are no more coloured masks, mask assignment will fail because of insufficient failsafes.
@AIDungeonTester2 @shenmxd0762 Note that you can draw region -1 at any point (and it should be done automatically after upload, provided that the upload was to the correct component) to see whether all the region colours are detected; they'll appear in the mask as black (I think), and regionless as white.

**Comment by Symbiomatrix** [comment]
I was able to add a negative base in attention mode, but it seems that latent doesn't have the capacity - any break in context is merged by cfgdenoiser's forward to a single uncond output. Even regular separation is just thrown together. In order to do more, there would need to be an override to building x_out in sd_samplers_kdiffusion.py.
