### ISSUE TITLE
Complex shapes

### ISSUE THREAD

**Issue by navarisun1982** [hako-mikan/sd-webui-regional-prompter#138]
hello, 

i wanted to ask if the plugin can do complex shapes containing nested COls inside rows, I have attached the shape I need to accomplish:
https://imgur.com/a/dPgXix7

**Comment by Symbiomatrix** [comment]
1) You can do anything with mask mode.
2) In matrix mode, yes and no, see my reply to #64 . Your best bet for this case would be vertical mode, and segment the blue region to the 3 columns. My regional's code is currently in a broken state so off the top of my head: 2;1;4,1;2;1;2;4;1,2;1;4 .

**Comment by navarisun1982** [comment]
1. I hope I can see the uploading mask option on your plugin, cause drawing masks in stable diffusion is painful and not giving accurate results. 
2. I tried the matrix you give and when hit visualize, it just gives rows without any columns in it

**Comment by Symbiomatrix** [comment]
1) There is an upload. Please read the instructions, you need specific colours (see "draw masks"). https://github.com/hako-mikan/sd-webui-regional-prompter#mask-regions-aka-inpaint-experimental-function
2) Can you upload the resulting image?

**Comment by navarisun1982** [comment]
Thx for help, that really works

**Comment by Symbiomatrix** [comment]
Yep. There is method to the madness.
