### ISSUE TITLE
The distinction between "common" and "base" prompt is unclear

### ISSUE THREAD

**Issue by lbeltrame** [hako-mikan/sd-webui-regional-prompter#14]
While the "common" prompt is explained in the README, it is (at least to me) unclear what the "base" prompt is. Perhaps an example could be added to the README itself.

**Comment by Symbiomatrix** [comment]
Common is easy to explain - prepends the section before all other prompts. Base is a bit more low level, to my understanding (which is admittedly inadequate): the base is applied after the prompts are converted to tokens and then transformed into weights, using the formula: (base_weight * base_prompt_weights + (1 - base_weight) * segment_weights). 
This means that at base_weight = 0 you get the segment unchanged, at base_weight = 1 it should be as if you wrote just the base prompt, and between 0:1 it's a sort of unpredictable mashup with the base. Perhaps it is comparable to the effects of a lora which has no keywords.
My intuition is that base is best used for setting the background or the scene in general, whereas common is better for clear cut details (shortcut for copypasta).

**Comment by hako-mikan** [comment]
```
a girl ADDROMM(or ADDBASE)
red hair BREAK
green dress
```
If there is a prompt that says , in the common case, region 1 is generated with the prompt `a girl red hair`. In the base case, if the ratio is 0.2, it is generated with the prompt (a girl) * 0.2 + (red hair) * 0.8. Basically, there is no problem with the common prompt. You may want to try the base if the common prompt is too strong.

**Comment by lbeltrame** [comment]
Thanks, it's clear now.

**Comment by BurnZeZ** [comment]
@hako-mikan 
How are global loras supposed to be inserted at the start of prompt?
I don't see a way an obvious way to do so, the base prompt is subject to additional processing, and common prompt results in a lora being inserted for every region.
