### ISSUE TITLE
Error when try to use regional prompter

### ISSUE THREAD

**Issue by mdlieber99** [hako-mikan/sd-webui-regional-prompter#140]
Just tried using regional prompter for the first time (very excited because latent couple was a disaster that broke a lot of other extension).  When I first tried to run it, I got this error:

RuntimeError: shape '[1, 37, 37, 640]' is invalid for input of size 1239040

Can you help with what I need to change?  I didn't enter in any numbers myself other 1,1 horizontal to split things into a left and right side

**Comment by AIDungeonTester2** [comment]
Can you share your prompt, negative prompt, and a screenshot of your Regional Prompter settings?

**Comment by mdlieber99** [comment]
So I can get it to work now as long as I don't use "hires. fix" but without hires.fix, the face I tuned into the model I'm using doesn't look right.  Have you dealt with that before?

**Comment by mdlieber99** [comment]
Any solution for the hires fix problem?

**Comment by shenmxd0762** [comment]
> Any solution for the hires fix problem?

As mentioned in other issues, only multiples of 8 resolution can be used, including after hires

**Comment by mdlieber99** [comment]
that worked!  704 instead of 700 fixed the issue.  thank you!
