### ISSUE TITLE
`ModuleNotFoundError` when built-in LoRA extension is disabled

### ISSUE THREAD

**Issue by catboxanon** [hako-mikan/sd-webui-regional-prompter#141]
Title -- originates from this line, regardless if the regional prompter extension is enabled or disabled within the accordion. I believe all that needs to be done here would be a try/except when it is unable to be imported.
https://github.com/hako-mikan/sd-webui-regional-prompter/blob/f71aa479e00736e2c9e19d986f977bdb4bf4f9c7/scripts/latent.py#L39-L40

That being said, not sure what the current behavior should be when the [LyCORIS extension](https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris) is enabled, and the built-in LoRA extension is not. Discussion at https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/issues/34 might be helpful.

**Comment by brknsoul** [comment]
This also happens in [SD.Next](https://github.com/vladmandic/automatic), when using the LyCORIS patch and disabling the LoRA module.

SD.Next is moving towards using the LyCORIS module to run both lycos _and_ loras.

```
06:53:08-094003 ERROR    Running script postprocess: E:\automatic\extensions\sd-webui-regional-prompter\scripts\rp.py:
                         ModuleNotFoundError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ E:\automatic\modules\scripts.py:442 in postprocess                                                                  │
│                                                                                                                     │
│   441 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                      │
│ > 442 │   │   │   │   script.postprocess(p, processed, *args)                                                       │
│   443 │   │   │   │   s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                     │
│                                                                                                                     │
│ E:\automatic\extensions\sd-webui-regional-prompter\scripts\rp.py:545 in postprocess                                 │
│                                                                                                                     │
│    544 │   │                                                                                                        │
│ >  545 │   │   unloader(self, p)                                                                                    │
│    546                                                                                                              │
│                                                                                                                     │
│ E:\automatic\extensions\sd-webui-regional-prompter\scripts\rp.py:564 in unloader                                    │
│                                                                                                                     │
│    563 │                                                                                                            │
│ >  564 │   unloadlorafowards(p)                                                                                     │
│    565                                                                                                              │
│                                                                                                                     │
│ E:\automatic\extensions\sd-webui-regional-prompter\scripts\latent.py:533 in unloadlorafowards                       │
│                                                                                                                     │
│   532 │   lactive = False                                                                                           │
│ > 533 │   import lora                                                                                               │
│   534 │   lora.loaded_loras.clear()                                                                                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: No module named 'lora'```

**Comment by brknsoul** [comment]
> users may use the LyCORIS extension in favor of the built-in LoRA extension

Vlad wants to move SD.Next to using the LyCORIS module to load LoRAs simply because the LoRA module is too old. It can fail in loading newer LoRAs.

**Comment by Symbiomatrix** [comment]
Some things seem to have a direct replacement:
- `import lora` to `import lycoris as lora` (or however it's renamed already),
- `lora.loaded_loras` to `lora.loaded_lycos`,
- `getattr(module, 'lora_layer_name', None)` to `getattr(module, 'lyco_layer_name', None)`
- `getattr(self, "lora_weights_backup", None)` to `getattr(self, "lyco_weights_backup", None)`
- Oddly, `getattr(self, "lora_current_names", ())` still exists, though there's also a lyco attribute as well; lycoris.py checks changes in both.

They say the architecture is unchanged (overall there seems to be a good deal of similarity to lyco_apply_weights, but there's an inpainting pad now, might need to inspect such changes more closely), and it seems extra_networks parsing remained in place, so it might be as simple as that, but might have to exclude or adjust to non loras if they act up.
