### ISSUE TITLE
Separate LoRA's for each region?

### ISSUE THREAD

**Issue by mdlieber99** [hako-mikan/sd-webui-regional-prompter#144]
How do you generate two particular people for the image.  I have created a LoRA for my face and a LoRA for my wife's face.  If I put each LoRA in a separate prompting area (i.e. separated by BREAKs), with a prompt for a man in one and a prompt for a woman in the other, it just gives me a man and a woman whose faces are both blends of the two LoRA's.  Any suggestion on how to resolve this?

**Comment by Symbiomatrix** [comment]
https://github.com/hako-mikan/sd-webui-regional-prompter#latent

**Comment by mdlieber99** [comment]
That didn't work at all for me.  Even though I put the LoRA's in two separate "BREAK" areas I just got a mix of two LoRA's unfortunately.

**Comment by mdlieber99** [comment]
I did not - thank you for the suggestion.  I will try that!
