### ISSUE TITLE
Memory leak when using LoRA in a Region

### ISSUE THREAD

**Issue by Susanoo1337** [hako-mikan/sd-webui-regional-prompter#15]
Works perfectly when using normal prompts VRAM usage stays level and very low, but once I put lora in one Region, VRAM usage keeps going up until I get an out of memory error:
![image](https://user-images.githubusercontent.com/25611627/228379505-954a4d83-691e-4dfa-862c-176f891fe7f3.png)

Without any lora:
![image](https://user-images.githubusercontent.com/25611627/228379772-3d00bd5a-d5b6-446c-9a58-ce18e35e8d87.png)

If I had to guess it's loading the lora into vram for every tile and then doesn't unload them.

**Comment by Symbiomatrix** [comment]
Are you using attention or latent mode, in the latest release? Have you tried it with other loras? How many tiles have you used? Was the memory usage going up during each step of processing or before starting?

**Comment by hako-mikan** [comment]
I could not reproduce it in my environment. If you are using an older version of LoRA Block Weight, that could be the cause.
