### ISSUE TITLE
Prompt mode breaks HR fix

### ISSUE THREAD

**Issue by asagi4** [hako-mikan/sd-webui-regional-prompter#161]
Hi,

I'm using RP with the latest A1111 webui commit, and updated RP today to current HEAD (2085a4c0e5)

It seems that the very recent changes to mask generation mentioned in the README don't work with HR fix; an earlier commit I was using (5f0681ea19) works, so this seems to be a  regression. I tried to figure it out myself, but the processing logic is too complicated for me to wrap my head around.

The issue is easily reproducible even with all other extensions disabled, so it doesn't seem to be an incompatibility. To reproduce, all I have to do is generate something in prompt mode with HR fix enabled.

The actual error is just an OOBE:
```
      File "/home/sd/git/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/attention.py", line 349, in promptsepcalc
        mask = masks[depth]
    IndexError: list index out of range
```

**Comment by hako-mikan** [comment]
Thanks, fixed.

**Comment by asagi4** [comment]
Just tested, and things work again. Thanks for the quick fix!
