### ISSUE TITLE
Error keeps popping up at random intervals

### ISSUE THREAD

**Issue by Edwin-Giovanni** [hako-mikan/sd-webui-regional-prompter#164]
the error it's the following:
Error running process: 

```
E:\STD\stable-diffusion-webui-directml\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "E:\STD\stable-diffusion-webui-directml\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "E:\STD\stable-diffusion-webui-directml\extensions\sd-webui-regional-prompter\scripts\rp.py", line 439, in process
        self, p = matrixdealer(self, p, aratios, bratios, self.mode, usebase, comprompt,comnegprompt)
      File "E:\STD\stable-diffusion-webui-directml\extensions\sd-webui-regional-prompter\scripts\regions.py", line 351, in matrixdealer
        mainprompt = p.prompt.split(KEYBRK,1)[1]
    IndexError: list index out of range
```
    
This happens when i try to: generate an image with 2 LORAS, or UPSCALE an image, the error gets to the point to make denoising not work so newly generated images are just noise, no matter the setting, the only way to fix the issue it's by deleting VENV folder and reinstalling it, i want to know how can i minimize this issue or solve it if possible, thank you for you time and have a great day!

PC SPECS:
CPU: R5 5600
GPU: RX 6600
RAM: 32GB 3200mhz

**Comment by Edwin-Giovanni** [comment]
this is the error that happens when the denoise stops working, making images look horrible, it could happen on the last step, or on the first one i do not know what causes this:

** Error executing callback cfg_denoised_callback for E:\STD\stable-diffusion-webui-directml\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "E:\STD\stable-diffusion-webui-directml\modules\script_callbacks.py", line 203, in cfg_denoised_callback
        c.callback(params)
      File "E:\STD\stable-diffusion-webui-directml\extensions\sd-webui-regional-prompter\scripts\rp.py", line 551, in denoised_callback
        denoised_callback_s(self, params)
      File "E:\STD\stable-diffusion-webui-directml\extensions\sd-webui-regional-prompter\scripts\latent.py", line 200, in denoised_callback_s
        x[a + b*areas, :, :, :] =  x[a + b*areas, :, :, :] * self.filters[a + b*areas] + x[x.size()[0]+(b-batch), :, :, :] * self.neg_filters[a + b*areas]
    IndexError: list index out of range
   
The image i tried to make was a 800x640 image, sometimes i have no issues making, but at seemingly random intervals this keeps happening, any help would be appreciated.

**Comment by Guillaume-Fgt** [comment]
> File "E:\STD\stable-diffusion-webui-directml\extensions\sd-webui-regional-prompter\scripts\regions.py", line 351, in matrixdealer
> mainprompt = p.prompt.split(KEYBRK,1)[1]
> IndexError: list index out of range

Hi,

```
    elif usebase: # Get base by first break as usual.
        baseprompt = p.prompt.split(KEYBRK,1)[0]
        mainprompt = p.prompt.split(KEYBRK,1)[1]
```

according to the code in `region.py` where the error is triggered, you probably have "use base prompt" checked but do not have "BREAK" in your prompt. So the `split()` function returns a list of one element. So, when the code tries to access the second element, it throws an `Index out of range` error.

**Comment by Symbiomatrix** [comment]
@Edwin-Giovanni Please provide full settings (including prompt and extension's). As @Guillaume-Fgt states, an error in the base splitting stage would indicate you are using the extension without any region separators (BREAK / ADDX).
The denoiser becomes active semi permanently once latent mode is used (due to webui's callback limitations); however, the callbacks are entirely wrapped in `if self.lactive or self.lpactive:` and `self.modep`, so it should not change regular calls with the extension deactivated, and certainly all should return to normal with a webui reset, no need to wipe the venv.
It is rather unlikely that the areas error should pop up at the last stage. The filters are only rebuilt when the input shape changes, so a mismatch should occur at the beginning,
How often does this random interval occur?

You can change this line to show more details on the current state when it does:
```
x[a + b*areas, :, :, :] =  x[a + b*areas, :, :, :] * self.filters[a + b*areas] + x[x.size()[0]+(b-batch), :, :, :] * self.neg_filters[a + b*areas]
```
to (mind the indentation)
```
try:
    x[a + b*areas, :, :, :] =  x[a + b*areas, :, :, :] * self.filters[a + b*areas] + x[x.size()[0]+(b-batch), :, :, :] * self.neg_filters[a + b*areas]
except IndexError:
    print("ERROR ", a, b, areas, batch, x.shape, len(self.filters), len(self.neg_filters))
    raise
```

**Comment by Edwin-Giovanni** [comment]
Hello, the settings im trying to use are: 
768x512, 30 Sampling steps, CFG Scale: 7
Prompts are:
Positive: 
((ultra-detailed)), ((illustration)), 2girls, street, outdoors,
BREAK
AND ((ultra-detailed)), ((illustration)), 2girls,<lora:JinxLol:.7> jinxlol, navel, gloves, fingerless gloves, midriff, bare shoulders, crop top, belt, head tilt,
AND ((ultra-detailed)), ((illustration)), 2girls,<lora:tatsumakiselect:.7> tatsumaki, black one piece dress, pelvic curtain, green eyes, head tilt,
Negative: 
(low quality, worst quality:1.4)
i did try with and without "use base prompt" and this appears to only happen when i use "latent" only instead of "attention" 
the other extensions i have are: Lycoris, TagComplete, Multidiffusion Upscaler, OpenPose Editor, sd-dynamic-prompts, model downloader, control net, regional prompter, composable lora, ultimate upscalling, Unprompted, LDSR, Lora, ScuNET, SwinIR, canvas-zoom-and-pan, extra-options-section and prompt-bracket-checker.
As for my need to wipe the venv when the issue happens, it keeps happening at any moment i try to use regional prompter, therefore making me unable to use the extension at all since all it produces are images with random colors or forms.

**Comment by Edwin-Giovanni** [comment]
Okay so after changing AND for ADDX it seems to generate properly and im not seeing any errors at the moment, i will keep generating and see if that was a complete fix for me.

**Comment by Edwin-Giovanni** [comment]
well after generating for one hour and so minutes, it seems that the issue has been fixed for now, thank you guys for helping and have a great day!.

**Comment by Symbiomatrix** [comment]
AND is automatically changed to BREAK and then back to AND in latent mode (unless the no change checkbox is ticked), and therefore should count as a region. I've organised it a bit better in a side version, not sure how exactly it acts currently, but anyway standard separators are the way to go.
