### ISSUE TITLE
Best prompting/Way to put two character loras?

### ISSUE THREAD

**Issue by Charmandrigo** [hako-mikan/sd-webui-regional-prompter#166]
This is related to possibly something that's been mentioned on the readme but I need some recommendations.
I have loras for two characters that look entirely different (furry animals), even with BREAKS, 1,1 regions use and Latent mode enabled, both loras still mix together forming weird fusions of the characters when a left column is specified to have <lora1:1> and right column is specified to have <lora2:1>,
Has someone figured out a way?
To be honest I wish there was a way to first render the left region with the input of said region, then after that one is almost done, render the right one before both finish with the general input

**Comment by Symbiomatrix** [comment]
Define weird fusions. Is it a single character whose left side is lora1 and right side is lora2? If so you need to add a common clause to force two characters in the scene. If the details are mixed across regions, I can't say I've encountered such a phenomenon in latent (unless the extensions isn't active or encountered an error).
