### ISSUE TITLE
How to use Regional Prompter via API endpoint?

### ISSUE THREAD

**Issue by juancopi81** [hako-mikan/sd-webui-regional-prompter#167]
Hi,

I am using Regional Prompter in the webui (1111) and I'd love to use it programmatically through a request with the **mask option**. I found the extension "[sd-webui-api-payload-display](https://github.com/huchenlei/sd-webui-api-payload-display)" very useful. It shows me this payload:

![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/4313860/a6618aa6-23bf-409a-a224-bdc4c2e38a07)

However, when I do that in my request, it does not work. I notice that lastrun.png never gets update. Could you please provide more information about this? I'd be also nice to add it to the User Guide.

Thank you very much,

Juan Carlos

**Comment by Symbiomatrix** [comment]
#18 
Lastrun.png getting updated is a side effect of one of the early calls in rp.process (savepresets), along with the rest of the last used parameters. If it's not updated, then this api extension might not be loading / running the script callback for whatever reason. Personally I've no interest in the api so that's as far as I go.

**Comment by cream3344** [comment]
Dear developers, why do you have no plans to compatible apis for the time being? Is it because of the heavy workload, similar to contronet plug-ins may be supported by more people

**Comment by hako-mikan** [comment]
In what way do you want to specify the mask?
If you want to specify a file to be a mask, this fix makes it possible.
It works as a mask by specifying the file name as text.

**Comment by cream3344** [comment]
> In what way do you want to specify the mask? If you want to specify a file to be a mask, this fix makes it possible. It works as a mask by specifying the file name as text.

![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/52308239/aa28555a-dcae-4e52-a459-a5e7fbdd89a1)

use in webui api text2img alwayson_scripts

**Comment by hako-mikan** [comment]
Read https://github.com/hako-mikan/sd-webui-regional-prompter/blob/main/README.md#how-to-use-via-api

**Comment by juancopi81** [comment]
Thanks a lot! I'll take a look at the documentation.
