### ISSUE TITLE
Does not work if a simple region control is attempted, and gives error in rp.py with list index out of range, if base and common prompt are added

### ISSUE THREAD

**Issue by indianninja2018** [hako-mikan/sd-webui-regional-prompter#168]
Previously was not working so I reinstalled the extension after disabling it, closing webui console, then deleting the folder and reinstalling it. Webui is updated.
ISSUE: when I use something like this 
1girl ADDCOL
1boy
with the extension active, divide ratio 1,1 and horizontal mode, the image is generated without problem but the regions dont work. Either a girl or a boy is generated, hence the region control does not work. This is without any negative prompt or using common negative prompts. 
After adding base prompt like 
garden ADDBASE
1girl and 1boy ADDCOMM
1girl ADDCOL
1boy 
And similar structured negative prompts, image is generated with both 1girl and 1boy in the same, but often parts of the prompt is not obeyed, so it looks like the extension is looking at the common prompt only. In this case where ADDBASE and ADDCOMM are added, the console throws the following error

 ```*** Error running process: C:\Stable diffusion automatic1111 git\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "C:\Stable diffusion automatic1111 git\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "C:\Stable diffusion automatic1111 git\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 439, in process
        self, p = matrixdealer(self, p, aratios, bratios, self.mode, usebase, comprompt,comnegprompt)
      File "C:\Stable diffusion automatic1111 git\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\regions.py", line 351, in matrixdealer
        mainprompt = p.prompt.split(KEYBRK,1)[1]
    IndexError: list index out of range```

**Comment by Symbiomatrix** [comment]
If you're using a multi clause negative as well, that could be a problem. Base in negative is buggy in the current version, as indicated in #133. I've written an [experimental version](https://github.com/hako-mikan/sd-webui-regional-prompter/tree/ver8) which allows negative base thus solving this issue (plus it reads common / base in any order), you're welcome to try it and report back.

**Comment by indianninja2018** [comment]
I am not using a multi clause negative usually, and use common negative prompt. It just does not work like it used to. How do I use the experimental version? git clone that into the extensions?

**Comment by Symbiomatrix** [comment]
@indianninja2018 Correct, override the existing extension with this version. It is similarly structured besides adding the promptcessor file. I haven't had time to incorporate this month's changes, which means it might not work with webui 1.5 and definitely not with SDXL, but other than that it's been stable on my end.
