### ISSUE TITLE
Can't Use Hi-Res fix if upscaling more than 2x. 

### ISSUE THREAD

**Issue by LuckyLuigiX4** [hako-mikan/sd-webui-regional-prompter#169]
Doesn't matter if its just 2.05x it keeps throwing this error at me

`RuntimeError: shape '[1, 9, 16, 1280]' is invalid for input of size 172800`

![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/76882834/509c10f3-c2f8-451d-8956-6cefdc9f537e)

Attached are my settings when this error this thrown. 

![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/76882834/f656ceb6-082f-450e-b064-56977e974159)

Also the settings used for Regional Prompter.

If you need anymore information I'll be happy to provide it. Thank you.

**Comment by hako-mikan** [comment]
Thanks reporting.
Fixed.
