### ISSUE TITLE
Compatibility with updated built-in LoRA extension

### ISSUE THREAD

**Issue by catboxanon** [hako-mikan/sd-webui-regional-prompter#170]
Semi-related to #141. See https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/11821 for the full details.

---

Currently, this extension references the `multiplier` attribute a lot. As of the latest dev version for the upcoming 1.5.0 release of the web UI, this has been replaced by a separate `te_multiplier` and `unet_multiplier`, as seen here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/a99d5708e6d603e8f7cfd1b8c6595f8026219ba0/extensions-builtin/Lora/network.py#L87-L95

From having a cursory look at the PR it also looks like there's now built-in functions like [`calc_scale`](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/a99d5708e6d603e8f7cfd1b8c6595f8026219ba0/extensions-builtin/Lora/network.py#L127), something that I believe is being done manually in the current extension code. 
https://github.com/hako-mikan/sd-webui-regional-prompter/blob/0624834836f18963191ed907b1d9281e4db568a2/scripts/latent.py#L392-L395

**Comment by hako-mikan** [comment]
Thanks for the info.
It looks like LyCORIS will be supported as well, so I will try to support it when it is officially released.

**Comment by hako-mikan** [comment]
I believe it has probably been fixed.
It worked fine in my environment with version 1.5RC.

However, there still seem to be issues with the built-in Lora code. 
It appears that using the old Lora option results in an error.

**Comment by hako-mikan** [comment]
Lora/Networks: use old method that takes longer when you have multiple Loras active and produces same results as kohya-ss/sd-webui-additional-networks extension
in settings
this options is needed for latent mode
however, its broken in 1.5RC

**Comment by hako-mikan** [comment]
It is not necessary, but it is better to use it. 
With the update around version 1.3, the method of applying LoRA has changed. 
This usually brings good results. 
However, in cases like this extension, when changing the strength of LoRA in every steps, the generation process becomes slower.
If the issue is not resolved when 1.5 is officially released, we will report it as an issue.
