### ISSUE TITLE
After a86d786, RP is always active

### ISSUE THREAD

**Issue by lbeltrame** [hako-mikan/sd-webui-regional-prompter#171]
I saw this using SD.next (vladmandic's fork of A1111). Using the latest revision (a86d786), RP is always active, no matter what the checkbox says. I noticed because my prompts started producing weird results all of a sudden even with known seeds and only a random exception inside RP made me realize it was active even if the box was unchecked.

**Comment by hako-mikan** [comment]
Thanks reporting.
Fixed.
