### ISSUE TITLE
Problems arising from using Mask mode in the API

### ISSUE THREAD

**Issue by Jabwin** [hako-mikan/sd-webui-regional-prompter#175]
rp.py, the function "process", row 324, the polymask need "not"?

**Comment by hako-mikan** [comment]
Required; in API mode, you must specify the file address of the mask file.

**Comment by Jabwin** [comment]
During my call, Mask is not working.
I'm trying to remove the 'not' here, it can run normally.
`if type(polymask) == str and not polymask`

Is this to verify that it is not empty?

**Comment by hako-mikan** [comment]
You are right. Fixed. Thanks!
