### ISSUE TITLE
It just doesn't work...

### ISSUE THREAD

**Issue by cyco-creates** [hako-mikan/sd-webui-regional-prompter#176]
So I'm using really simple prompt like:

a man and a woman, empty apartment, wide shot
BREAK
a man with black short hair and glasses
BREAK
a woman with blonde hair and a ponytail

settings:
Steps: 20 | Seed: 2518173866 | Sampler: Euler a | CFG scale: 7 | Size: 768x512 | Parser: Full parser | Model: cyberrealistic_v31 | Model hash: 03363589fe | Face restoration: CodeFormer | RP Active: True | RP Divide mode: Matrix | RP Matrix submode: Horizontal | RP Mask submode: Mask | RP Prompt submode: Prompt | RP Calc Mode: Attention | RP Ratios: "1,1" | RP Base Ratios: 0.2 | RP Use Base: False | RP Use Common: True | RP Use Ncommon: False | RP Change AND: False | RP LoRA Neg Te Ratios: 0 | RP LoRA Neg U Ratios: 0 | RP threshold: 0.4

In most cases I get random man / woman in various regions. Sometimes only woman, sometimes only man, sometimes both and sometimes an empty apartment. Then I turn off regional prompter and I'm basically getting the same results. Can someone please help me figure out what i'm doing wrong?

**Comment by hako-mikan** [comment]
Uncheck `Use Common prompt`.

**Comment by cyco-creates** [comment]
I wish it would be as simple as that... If I uncheck Common prompt I'm consistently getting one guy in an empty flat, woman is not rendering.

**Comment by hako-mikan** [comment]
I'm sorry. It seems like it's not an issue with the common prompt.
I tried it myself, but this seems to be a challenging problem. This extension specifies prompts for specific domains, but if the model itself lacks the capability to produce humans, it becomes difficult. Even without using this extension, consistently generating two people is challenging.

If you remove the 'wide shot', it should start generating people, so please give it a try. 

To test if this extension is working, using colors would be optimal. Write something like 'blue wall' for one and 'red wall' for the other and see how it responds.

**Comment by cyco-creates** [comment]
As you can see I'm using cyberrealistic model which is extremely good with producing humans. Without the extension I'm getting two people consistently. The reason I'd like to use the extension is to get two loras working separately, for each person on each side. We both know two loras in single prompt gets you a lora mix. And I'd love a solution where I could get two people in same prompt with loras working. Possibly without using masks.

I have tested the red and blue wall solution and extension works.

**Comment by hako-mikan** [comment]
The separation of LoRA is possible in the Latent mode, but depending on the nature of LoRA, it may be challenging.
