### ISSUE TITLE
API for this plugin

### ISSUE THREAD

**Issue by Minebot17** [hako-mikan/sd-webui-regional-prompter#18]
Do you plan add API to the plugin in future? It would possible to automate generation. I don't know about other people, but at least I need this feature so much

**Comment by hako-mikan** [comment]
Sorry, I have no knowledge of the API. I have no plans to support it at this time.

**Comment by tjthejuggler** [comment]
This would be amazing! Does anyone have a sense of how difficult this would be to do?
