### ISSUE TITLE
api mask mode bug

### ISSUE THREAD

**Issue by joindn** [hako-mikan/sd-webui-regional-prompter#181]
In MASK mode, when I made an API call, I encountered a BUG.
`
*** Error running process: D:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 474, in process
        script.process(p, *script_args)
      File "D:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 357, in process
        savepresets("lastrun",rp_selected_tab, mmode, xmode, pmode, aratios,bratios,
      File "D:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 760, in savepresets
        settings = saveblob(settings)
      File "D:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 734, in saveblob
        x = x.save(preset[0], preset)
      File "D:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 673, in save
        save_mask(self.img, self.makepath(name))
      File "D:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\regions.py", line 577, in save_mask
        img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
    cv2.error: OpenCV(4.8.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
    > Overload resolution failed:
    >  - src is not a numpy array, neither a scalar
    >  - Expected Ptr<cv::UMat> for argument 'src'
 My parameters were:           
"Regional Prompter": {
  "args": [True,False,"Mask","","Mask","","","0",True,True,False,"Attention",True,"0","0","0","lastrun.png"]
}
`

I attempted to fix the file path issue, and now I wonder if I can submit a PR for it?

Furthermore, I have added the mask file, which allows API uploads, making the API usage more flexible.

**Comment by hako-mikan** [comment]
I would be happy to have you do that.

**Comment by Symbiomatrix** [comment]
If I'm reading this correctly, you're effectively limiting the colours to be in the serial range (20 + total number used)? It would be better to preprocess the loaded image so that either border colours are corrected according to their neighbours (via a step of small dilation and erosion, perhaps), or adding a count to get_colours and emptying pixels under a certain count (parameterised, preferably). REGUSE is a bandaid, the moment you draw a region it gets added to the list, and then throws off region counts.

**Comment by Zhuangvictor0** [comment]
> 在MASK模式下，当我进行API调用时，遇到了一个BUG。 `*** Error running process: D:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py Traceback (most recent call last): File "D:\stable-diffusion-webui\modules\scripts.py", line 474, in process script.process(p, *script_args) File "D:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 357, in process savepresets("lastrun",rp_selected_tab, mmode, xmode, pmode, aratios,bratios, File "D:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 760, in savepresets settings = saveblob(settings) File "D:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 734, in saveblob x = x.save(preset[0], preset) File "D:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 673, in save save_mask(self.img, self.makepath(name)) File "D:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\regions.py", line 577, in save_mask img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR) cv2.error: OpenCV(4.8.0) :-1: error: (-5:Bad argument) in function 'cvtColor' > Overload resolution failed: > - src is not a numpy array, neither a scalar > - Expected Ptr<cv::UMat> for argument 'src' My parameters were: "Regional Prompter": { "args": [True,False,"Mask","","Mask","","","0",True,True,False,"Attention",True,"0","0","0","lastrun.png"] }`
> 
> 我尝试修复文件路径问题，现在我想知道我是否可以为其提交 PR？
> 
> 另外我还添加了掩码文件，允许API上传，使得API的使用更加灵活。

请问是否可以分享出来呢，感谢
