### ISSUE TITLE
Latent mode compatibility with "LoRa Control - Dynamic Weights Controller" extension

### ISSUE THREAD

**Issue by Hoogyme** [hako-mikan/sd-webui-regional-prompter#182]
Specifically this extension: https://github.com/cheald/sd-webui-loractl

Currently these extensions work fine together in attention mode and the extended syntax from loractl works as intended with regional prompting.
![](https://files.catbox.moe/93y6gx.png)

Functionality breaks when switching to latent mode, even without utilizing the extended syntax. The result ends up similar to attention mode where the loras are not separated. 

latent result with loractl disabled | latent result with loractl enabled
------ | ------
![Latent result with loractl disabled](https://files.catbox.moe/2ig495.png) _Works as intended, LoRAs are separated_ | ![Latent result with loractl enabled](https://files.catbox.moe/mg2nu5.png) _Does not work as intended, no separation of LoRAs_

Furthermore in latent mode, using the extended syntax of loractl produces errors and will not output a result.
```
Error executing callback cfg_denoised_callback for D:\Git\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "D:\Git\stable-diffusion-webui\modules\script_callbacks.py", line 203, in cfg_denoised_callback
        c.callback(params)
      File "D:\Git\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 476, in denoised_callback
        denoised_callback_s(self, params)
      File "D:\Git\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\latent.py", line 181, in denoised_callback_s
        fil = self.filters[a + b*areas]
    IndexError: list index out of range
```

**Comment by hako-mikan** [comment]
Maybe fixed.
The process is very complex and may not work in some cases. If this happens, restart web-ui completely.
