### ISSUE TITLE
Error occurs if Batch count is greater than 2

### ISSUE THREAD

**Issue by yamanobe96** [hako-mikan/sd-webui-regional-prompter#184]
Version or Commit where the problem happens
version: v1.5.0  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.32.0  •  checkpoint: 2336dbf342

Error occurs when Batch count is greater than 2 with Regional Prompter and Hires. fix active
Please solve this problem as I cannot create the images I want without this wonderful extension!

[loglog.txt](https://github.com/hako-mikan/sd-webui-regional-prompter/files/12172492/loglog.txt)

**Comment by hako-mikan** [comment]
May be fixed.
But couldn't reproduce your error.
If not fixed, tell me how to use your upscaler.

**Comment by yamanobe96** [comment]
Thank you.
Hires. the settings for the fix.
Upscaler checked 5 of them and all had errors
 latent error
 eula a error
 lanczos error
 4x-ultramix_balanced error
 swinIR_4x error

hires steps 20 Denoising strength0.35 

Sorry for the new information, but there is a new image size that can be generated
image size
Upscale by3 resize: from 512x768 to 1536x2304 error
Upscale by2.5 resize: from 512x768 to 1280x1920 error
Upscale by2.05resize: from 512x768 to 1049x1574 error
Upscale by2 resize: from 512x768 to 1024x1536 OK!
Upscale by1.05resize: from 512x768 to 537x806 error
Upscale by1 resize: from 512x768 to 512x768 OK!

**Comment by hako-mikan** [comment]
I tested  768x512 to 1574x1049 for 2 batch count.
It worked well.
Maybe try reinstalling the extension?

**Comment by yamanobe96** [comment]
Thanks, I will try reinstalling.
However, I am doing the install on July 23.
I think it is probably the latest version, so there is a possibility of similar results.
Anyway, I will try and report back!

**Comment by hako-mikan** [comment]
Has the issue been resolved since then?
