### ISSUE TITLE
Provide, if possible, an example with more than one character/person 

### ISSUE THREAD

**Issue by lbeltrame** [hako-mikan/sd-webui-regional-prompter#19]
I put if possible because I'm not sure, unlike Latent Couple, if by design it is possible to put more than one person or character reliably in the scene. From the header in the README, it is indeed possible, but an example would be very helpful. 

This is because my current tests rarely produce more than one character even in the simplest setting (two columns of equal size) unless I use ControlNet. Often I get just one, or a hybrid of two. And I'm sure I'm the one doing it wrong.

**Comment by Symbiomatrix** [comment]
Shouldn't be a problem at all, but you need to set the scene since multiple characters is a thing most checkpoints and loras struggle with and avoid naturally, unless specifically designed for it. To my understanding, if the scene starts as single character, the noise will clash with the prompt regions in weird ways to make up the difference; I've have a character whose hair was one colour hair on the left, and different on the right, split down the middle.
For example (untested):
two people, standing side by side ADDCOMM man ADDCOL woman
Region: 1,1

"Reliably" may vary, but I've had like 95% with sufficient base weight, no controlnet.

**Comment by lbeltrame** [comment]
Thanks, I'll test.

**Comment by mschaeffers** [comment]
This example came out pretty good. The prompt was for 4 people but it displayed 5.  (prompt details below)
![00117-310747619](https://user-images.githubusercontent.com/87294152/232377530-34525384-b495-46a2-a235-baf6ff763c1e.png)

Prompt: four people, standing side by side in a school ADDCOMM 
full body, young Japanese, woman, round head shape, Alabaster skin, pouty lips, bright eyes, amber eye colour, small nose, Box braid hair, auburn hair colour, Robe, Knee-high boot, aquamarine, large body type, soft lighting  ADDCOL full body, young, Cambodian, man, heart-shaped head shape, Medium skin, bright eyes, brown eye colour, fat nose, round cheeks, Shaggy Layers hair, dark brown hair colour, suit, Falu Red, small breasts, thin body type, soft lighting  ADDCOL full body, young Dutch girl, freckles, heart-shaped head shape, Medium skin, bright eyes, hazel eye colour, small nose, freckles cheeks, expression of admiration, Layered Pixie Cut hair, chestnut brown hair colour, school uniform, Knee-high boot, Falu Red, thin body type, soft lighting  ADDCOL full body, adult Australian, woman, heart-shaped head shape, Medium skin, bright eyes, hazel eye colour, small nose, freckles cheeks, expression of admiration, Dutch Braid hair, chestnut brown hair colour, dark sweater, Knee-high boot, Falu Red, chubby body type, smiling, soft lighting

Negative prompt: lowres, text, error, cropped, worst quality, low quality, jpeg artifacts, duplicate, morbid, mutilated, out of frame, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck

Steps: 60, Sampler: DPM++ SDE Karras, CFG scale: 7.5, Seed: 310747619, Face restoration: CodeFormer, Size: 768x512, Model hash: e6415c4892, Model: realisticVisionV20_v20, RP Active: True, RP Divide mode: Horizontal, RP Calc Mode: Attention, RP Ratios: "1,1,1,1", RP Base Ratios: 0.2, RP Use Base: False, RP Use Common: False, RP Use Ncommon: True, RP LoRA Neg Te off: False, RP LoRA Neg U off: False

**Comment by mschaeffers** [comment]
I having been doing more test. Add the following prompt at the start gives me good results 90% of the time. 

(two people, standing side by side) ADDCOMM person 1 description ADDCOL  person 2 description
