### ISSUE TITLE
REGIONAL PROMPTER & DEFORUM

### ISSUE THREAD

**Issue by marianobiotico** [hako-mikan/sd-webui-regional-prompter#190]
Is there any way to bring this tool to DEFORUM?

**Comment by hako-mikan** [comment]
I have never used DEFORUM so I am not sure. Did you encounter any errors when you tried to use it?

**Comment by marianobiotico** [comment]
Hello Hako-Mikan how are you?

Today Regional Prompter is not adapted for deforum so it cannot be called as a plugin. That's why the creation of 2 totally different characters is something solved in text2img but not in Deforum. I wanted to know if there is any way to adapt it or some other resource to be able to create 2 completely consistent different characters without mixing their traits and clothes. Thx! : )
