### ISSUE TITLE
KeyError issue with LORA: list.append() takes exactly one argument (2 given)

### ISSUE THREAD

**Issue by crystailx** [hako-mikan/sd-webui-regional-prompter#192]
I got the KeyError while using LORA + Latent with the latest commit version(https://github.com/hako-mikan/sd-webui-regional-prompter/commit/cc219737d41f184a7ba36af852b2c11db93b6310) 

Here's the first stack trace I got
```
Regional Prompter Active, Pos tokens : [107, 106], Neg tokens : [450]
*** Error running process_batch: /Users/myself/Codes/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py
    Traceback (most recent call last):
      File "/Users/myself/Codes/stable-diffusion-webui/modules/scripts.py", line 490, in process_batch
        script.process_batch(p, *script_args, **kwargs)
      File "/Users/myself/Codes/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py", line 455, in process_batch
        setloradevice(self) #change lora device cup to gup and restore model in new web-ui lora method
      File "/Users/myself/Codes/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/latent.py", line 40, in setloradevice
        oldnew.append(old,new)
    TypeError: list.append() takes exactly one argument (2 given)
```
I'm not familiar with Python, so I'm not sure if it's a Python version issue? (I'm using Python 3.10.6)
But it seems like this function has been modified recently, and the `oldnew` list is not used. 
It seems to work properly if I remove it (Line 31 & Line 40).
https://github.com/hako-mikan/sd-webui-regional-prompter/blob/cc219737d41f184a7ba36af852b2c11db93b6310/scripts/latent.py#L31-L40

**Comment by hako-mikan** [comment]
may be fixed
