### ISSUE TITLE
"disable convert 'AND' to 'BREAK'" option doesn't seem to work

### ISSUE THREAD

**Issue by Baggaroth** [hako-mikan/sd-webui-regional-prompter#198]
There isn't really anything else to say about this except the title. One of my Loras has "AND" in the name, and this picks it up as a separator for the regional prompter, even if this checkbox is checked. This causes Stable Diffusion to output "empty" (ie no prompts), since I also have common prompt checked. I managed to fix it for my use by simply changing the case of the AND in the file to "and", but I think this should be re-evaluated because it doesn't work. Very minor issue, just noting it.

**Comment by hako-mikan** [comment]
maybe fixed
