### ISSUE TITLE
Error Executing callback cfg_denoised_callback

### ISSUE THREAD

**Issue by LeGromp** [hako-mikan/sd-webui-regional-prompter#199]
I'm not sure what's happening but when I attempt to use regional prompter in latent mode & base/common prompt(and many active loras), my sd comes back with this error. 

** Error executing callback cfg_denoised_callback for C:\Users\K\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
    Traceback (most recent call last):
      File "C:\Users\K\stable-diffusion-webui\modules\script_callbacks.py", line 203, in cfg_denoised_callback
        c.callback(params)
      File "C:\Users\K\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 512, in denoised_callback
        denoised_callback_s(self, params)
      File "C:\Users\K\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\latent.py", line 210, in denoised_callback_s
        fil = self.filters[a + b*areas]
    IndexError: list index out of range

This is the first 'portion' of the error, and this portion repeats itself continuously. What comes out at the end is just a mesh of colours. I'm not sure if I'm doing something wrong? I don't have controlnet or anything active while using this. I am also using stable diffusion 1.5 and version 1.5.1. I also double checked that it wasn't just an update issue, as I had uninstalled and reinstalled regional prompter multiple times. SD also works fine without regional prompter active.

**Comment by hako-mikan** [comment]
It might be influenced by a complicated prompt. 
For now, please try to see if it works normally with a simple prompt and two LoRAs or so.

**Comment by LizardKing777** [comment]
I have the same problem. Can't get latent to work at all.

Reading this, I tried to use as simple prompt as possible. No change.
![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/154367673/61614c35-3a06-43f1-b61e-4dc2527c2fc1)


Using Controlnet with Openpose and Normal Map. I get the same error whether I put the Loras in the prompt or using Lora Mask.

Nothing I try makes Latent mode work at all. It just gives me the error and ignores all the Loras.
