### ISSUE TITLE
If the negative prompt is 75 tokens or more, an error occurs.

### ISSUE THREAD

**Issue by sntsris** [hako-mikan/sd-webui-regional-prompter#2]
Thanks for making a nice plugin. 

As the title says, it seems that the error occurs when the negative prompt exceeds 75 tokens.

```
IndexError: list index out of range
```

**Comment by hako-mikan** [comment]
I am aware of this issue. I'm thinking about how to deal with it, so please wait.

**Comment by hako-mikan** [comment]
Updated. Now you can input over 75 tokens.

**Comment by jordanjay29** [comment]
I just tried the latest commit and am unable to proceed with more than 75 tokens in a negative prompt. 

Additionally I found that a BREAK increases the token count by 75 tokens itself, making the Common Negative option difficult to use.

**Comment by jordanjay29** [comment]
> pos tokens : [12, 56], neg tokens : [2]
I'm not certain how to achieve this. 

The basic error is a variable size overflow: 
> RuntimeError: shape '[1, 4096, 320]' is invalid for input of size 655360

[I added the full error output to a gist.](https://gist.github.com/jordanjay29/93cba52e974bf24b66b439f01266227a)

**Comment by opvelll** [comment]
In my case, it seems the error occurred because I wrote BREAK at the end of the last line of the prompt.

**Comment by jordanjay29** [comment]
That was not my case. Because I removed the prompt for privacy reasons, mine was structured like: 

> general prompt, BREAK
> subprompt1, BREAK
> subprompt2

Neg: 
> general negative, BREAK
> sub-negative1, BREAK
> sub-negative2

**Comment by hako-mikan** [comment]
Is the situation still the same in the latest version?　
If so, please tell me the text "tokens..." that appears on the command prompt screen.

**Comment by Jonseed** [comment]
I also get this error, but it doesn't seem to have to do with the length of the negative prompt. Not sure the cause. On commit 2dc66cbe (Tue May 9 12:49:30 2023).

```
Error running process: F:\repos\auto111\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
Traceback (most recent call last):
  File "F:\repos\auto111\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 263, in process
    self, p = matrixdealer(self, p, aratios, bratios, mode, usebase, comprompt,comnegprompt)
  File "F:\repos\auto111\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\regions.py", line 351, in matrixdealer
    mainprompt = p.prompt.split(KEYBRK,1)[1]
IndexError: list index out of range
```
