### ISSUE TITLE
Couldn't find Divide Mode, and cannot use Prompt to seg the mask

### ISSUE THREAD

**Issue by Yuhyeong** [hako-mikan/sd-webui-regional-prompter#200]
![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/49343045/d34147cc-5c4d-446b-9e70-6511d0e5eb97)

the interface dont have the divide mode

**Comment by hako-mikan** [comment]
README was old. Fixed.
split mode = divide mode.

How cannot use Prompt to seg the mask?

**Comment by TomTomGit86** [comment]
i still cant see how to switch from the matrix mode to the mask mode am i missing something?
