### ISSUE TITLE
batch img2img or batch controlnet only works for first image

### ISSUE THREAD

**Issue by StephanosPSteer** [hako-mikan/sd-webui-regional-prompter#205]
So this is what I get for the first image:-

zombie elton john and zombie jeremy clarkson
ADDCOMM
zombie elton john
ADDCOL
zombie jeremy clarkson
ADDCOL
Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 4186397374, Size: 512x512, Model hash: 15012c538f, Model: realisticVisionV51_v51VAE, NGMS: 15, ControlNet 0: "preprocessor: openpose, model: control_v11p_sd15_openpose [cab727d4], weight: 1, starting/ending: (0, 1), resize mode: Crop and Resize, pixel perfect: True, control mode: Balanced, preprocessor params: (512, 64, 64)", RP Active: True, RP Divide mode: Matrix, RP Matrix submode: Horizontal, RP Mask submode: Mask, RP Prompt submode: Prompt, RP Calc Mode: Latent, RP Ratios: "1,1", RP Base Ratios: 0.2, RP Use Base: False, RP Use Common: False, RP Use Ncommon: False, RP Change AND: False, RP LoRA Neg Te Ratios: 0, RP LoRA Neg U Ratios: 0, RP threshold: 0.4, RP LoRA Stop Step: 0, RP LoRA Hires Stop Step: 0, Version: v1.5.1

that gives 

but from second image on no prompt

Steps: 20, Sampler: Euler a, CFG scale: 7, Seed: 4186397374, Size: 512x512, Model hash: 15012c538f, Model: realisticVisionV51_v51VAE, NGMS: 15, ControlNet 0: "preprocessor: openpose, model: control_v11p_sd15_openpose [cab727d4], weight: 1, starting/ending: (0, 1), resize mode: Crop and Resize, pixel perfect: True, control mode: Balanced, preprocessor params: (512, 64, 64)", RP Active: True, RP Divide mode: Matrix, RP Matrix submode: Horizontal, RP Mask submode: Mask, RP Prompt submode: Prompt, RP Calc Mode: Latent, RP Ratios: "1,1", RP Base Ratios: 0.2, RP Use Base: False, RP Use Common: False, RP Use Ncommon: False, RP Change AND: False, RP LoRA Neg Te Ratios: 0, RP LoRA Neg U Ratios: 0, RP threshold: 0.4, RP LoRA Stop Step: 0, RP LoRA Hires Stop Step: 0, Version: v1.5.1

![01347-4186397374](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/26924183/fa083261-148c-45ff-b6c1-d01a37774ffb)

am I doing something wrong or does this not working?

**Comment by hako-mikan** [comment]
I was unable to reproduce the error you encountered, but I have attempted to fix it. Please give it a try.

**Comment by RAHoebe** [comment]
TXT2IMG also works only correct for the first imag.

**Comment by hako-mikan** [comment]
As far as I have tried, I am not encountering the same issue. 
It might be an interaction between extensions; are you using any other extensions simultaneously?
