### ISSUE TITLE
BREAK may be recorded with AND

### ISSUE THREAD

**Issue by elistys** [hako-mikan/sd-webui-regional-prompter#212]
When batch generation is performed using Prompt-Ex and ADetailer together with AUTOMATIC1111, BREAK is recorded as BREAK in the first PNG, but BREAK is replaced with AND and recorded from the second PNG.

・AUTOMATIC1111
・Regional prompts
・A Detailer

Which one is the problem?
Or is this an intentional behavior rather than a problem?

**Comment by elistys** [comment]
I forgot to write the environment.
M2 Mac 13.5
・AUTOMATIC1111 : v1.5.2
・Regional Prompter : e75f5b96
・A Detailer : v23.8.1

**Comment by elistys** [comment]
Turning off ADetailer will not replace AND.
Conversely, it will not be replaced even if ADetailer is on and Regional Prompter is off.
Of course, if it's not a batch, it won't replace any combination.

However, if I t2t from PNG (A) replaced with AND, the same mask will be created and the output PNG will have exactly the same result as A.

So if AND works the same as BREAK, I don't mind if it's replaced.
I'm worried because I didn't find any description that AND can be used instead of BREAK on the description page of Regional Prompter.

ーーーーーーーーーーーーーーーーー
Japanese translation日本語訳（正確には訳ではなく原文ですが・・・）

ADetailerをオフにするとANDに置き換わる事はありません。逆に、ADetailerオン、Regional Prompterオフでも置き換わりません。もちろん、バッチでなければどの組み合わせでも置き換わりません。

ただ、ANDに置き換わったPNG（A）からt2tをすると、同じようにマスクも作成されて出力されたPNGもAとまったく同じ結果になります。

なので、ANDがBREAKと同一の働きをするなら置き換わっても構わないのですが、Regional Prompterの説明ページにはBREAKの代わりにANDを使っても大丈夫という記述は見当たらなかったので気になっています。

**Comment by hako-mikan** [comment]
なるほど理解しました。
Latent modeではANDを使用して処理されるので内部ではBREAKはANDに変換されて処理されます。この場合、ANDはBREAKと同じ意味になります。
逆にANDが入力されている場合でAttention modeで使用すると内部ではBREAKに変換されて処理されます。

**Comment by hako-mikan** [comment]
READMEに追記しておきますね。

**Comment by elistys** [comment]
So for Attention and Latent, i can use either BREAK or AND.

There is a possibility that ADetailer is the cause of AND being recorded in PNG, but it seems that the cause cannot be narrowed down.

thank you very much.

ーーーーーーーーーーーーーーーーー
Japanese translation日本語訳

AttentionとLatentでは、BREAKとANDのどちらを使ってもOKということですね。

PNGにANDと記録される原因はADetailerの可能性がありますが、原因は絞り込めない感じでしょうかね。

お忙しいところ、ありがとうございました^^

**Comment by hako-mikan** [comment]
基本的には画像生成に使用されたプロンプトがPNG infoに入力されますが、この拡張では内部で変換操作が行われるので入力されたプロンプトをPNG infoに書き込む操作を行っています。おそらくADetailerはその操作の後にもう一度生成に使われたプロンプトを書き込む操作を行っているのでしょう。これをまた上書きするのは危険かもしれません。
