### ISSUE TITLE
An error is displayed when 1.6.0 is started.

### ISSUE THREAD

**Issue by Neytiri7** [hako-mikan/sd-webui-regional-prompter#214]
O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py:75: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  areasimg = gr.Image(type="pil", show_label  = False).style(height=256,width=256)

**Comment by hako-mikan** [comment]
Fixed.

**Comment by Neytiri7** [comment]
Thank you from the bottom of my heart.
