### ISSUE TITLE
Batch mode can`t work well with LoRA

### ISSUE THREAD

**Issue by fenixnix** [hako-mikan/sd-webui-regional-prompter#217]
if batch_count >1. except first result,nexts outputs is weird

**Comment by RAHoebe** [comment]
Same problem here. First image is perfect, the next ones are kind of random results. Can you please look in to this?

**Comment by hako-mikan** [comment]
As far as I have tried, I am not encountering the same issue.
It might be an interaction between extensions; are you using any other extensions simultaneously?

**Comment by hako-mikan** [comment]
Do you using dynamic prompt?
