### ISSUE TITLE
Compatibility with AND

### ISSUE THREAD

**Issue by Sakura-Luna** [hako-mikan/sd-webui-regional-prompter#22]
I noticed that the Attention and Latent modes handle "AND" differently. The latter will replace BREAK with AND, and it can be executed normally with AND, but the former will directly throw an error it does not accept AND.

**Comment by hako-mikan** [comment]
It depends on the development process. The basic is “BREAK” and I changed it to convert AND when I added the Latent mode. It is easy to convert AND to BREAK, but I need to think a little about the implementation because AND cannot be used in Attention mode. Is there anyone who wants to use AND in Attention mode? If not, it seems like a good idea to implement it.

**Comment by Sakura-Luna** [comment]
Considering consistency, it is a good choice to make the Attention mode support AND, and it is also compatible with other Extension prompts.
By the way, did you use a machine translation, it looks a bit confusing.

**Comment by Sakura-Luna** [comment]
@hako-mikan I tested the new update, and now the logic seems to be that the extension does not take effect when using AND in Attention mode. I think this is not an appropriate approach. If the extension does not support AND, it should directly throw a clear error.

**Comment by hako-mikan** [comment]
That mode is under testing and may not work properly. I will make an announcement when it works properly.

As you pointed out, I partially use machine translation.
In Japanese, the subject is often omitted and the expressions are ambiguous, so the accuracy of machine translation is still not very high.

**Comment by Sakura-Luna** [comment]
It works fine, thanks. To make a digression, the extension does not support the DDIM/UniPC sampler, but the error thrown in the Attention mode is not clear. It should be possible to add a judgment, indicating that the sampler used does not support it.

**Comment by Sakura-Luna** [comment]
@Symbiomatrix The latest update broke compatibility with AND, and the pre-update results cannot be reproduced.

Prompt (Attention mode)
![image](https://user-images.githubusercontent.com/53183413/230777970-dd613b13-0283-4b43-a610-bf8287e41c90.png)
Result
![image](https://user-images.githubusercontent.com/53183413/230777982-e111f33b-7821-433a-a2f0-6a6b4cdd8b5a.png)

**Comment by Symbiomatrix** [comment]
Out of the loop, dude.
Are you saying that when regional is active (and "disable convert" is inactive), AND shouldn't be converted to BREAK and the prompt should be run as a single region?

**Comment by Sakura-Luna** [comment]
@Symbiomatrix The extension just added support for AND in Attention mode a few days ago, it doesn't convert AND to BREAK. New updates make old results irreproducible.

**Comment by Sakura-Luna** [comment]
@Symbiomatrix My fault, I seem to have misremembered.

**Comment by Symbiomatrix** [comment]
Sorry, I'm still not following. The treatment of AND in the current version is:
```
[process]
            if not nchangeand and "AND" in p.prompt.upper():
                p.prompt = p.prompt.replace("AND",KEYBRK)
                for i in lange(p.all_prompts):
                    p.all_prompts[i] = p.all_prompts[i].replace("AND",KEYBRK)
                self.anded = True
```
Which changes every and to break.

Followed by:
```
 if self.usecom or self.indexperiment or self.anded:
            p.prompt = self.orig_all_prompts[0]
            p.all_prompts[self.imgcount] = self.orig_all_prompts[self.imgcount]
```
Which changes them back.

It seems to be buggy, however: 
```
            self.orig_all_prompts = p.all_prompts
            self.orig_all_negative_prompts = p.all_negative_prompts 
```
Does not generate a deep copy of the alls, so the reinstatement doesn't actually do anything.
