### ISSUE TITLE
Latent mode doesn't work in SDXL

### ISSUE THREAD

**Issue by anae-git** [hako-mikan/sd-webui-regional-prompter#221]
When using latent mode I am getting:
```
*** Error executing callback cfg_denoised_callback for /u/sd-webui/extensions/sd-webui-regional-prompter/scripts/rp.py
    Traceback (most recent call last):
      File "/u/sd-webui/modules/script_callbacks.py", line 224, in cfg_denoised_callback
        c.callback(params)
      File "/u/sd-webui/extensions/sd-webui-regional-prompter/scripts/rp.py", line 527, in denoised_callback
        denoised_callback_s(self, params)
      File "/u/sd-webui/extensions/sd-webui-regional-prompter/scripts/latent.py", line 213, in denoised_callback_s
        fil = self.filters[a + b*areas]
    IndexError: list index out of range
```

**Comment by anae-git** [comment]
I should clarify that this is while trying to use 2 loras. It mostly works with just 1 lora.

**Comment by miaoshouai** [comment]
i'm having the same issue with two loras

**Comment by CemalSahin** [comment]
it works for me, sdxl, 2 character lora, divide ratio 1,1 latent mode

**Comment by hako-mikan** [comment]
I confirmed it works.
Please refer to it for your reference.
This picture was generated using two loras
https://civitai.com/models/137641/aqua-konosuba-lora-xl
https://civitai.com/models/135507/kusanagi-motoko-ghost-in-the-shell-lora-xl
Prompt and setting is here,
```
anime illustration of masterpiece, beautiful 2girls, full-body,BREAK
Konosuba aqua <lora:aqua_xl_v1:0.5> BREAK
Kusanagi Motoko ghost in the shell <lora:kusanagi_motoko:0.5>
```
Matrix mode, Columns, Use Common, Latent, 1,1

![00087-977594327](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/122196982/512aa5be-9673-41ea-b8dc-cb885efe5ee9)

**Comment by hako-mikan** [comment]
For further discussions, use https://github.com/hako-mikan/sd-webui-regional-prompter/issues/220
