### ISSUE TITLE
Regional Prompter do not work

### ISSUE THREAD

**Issue by ZhejunRen** [hako-mikan/sd-webui-regional-prompter#233]
Hi hako-mikan

Thank you for writting this extension, my problem is that in my environment it do not work at all.

My a1111 version is 1.6.0, and my setting is shown below, 

<img width="1440" alt="截屏2023-09-21 15 59 13" src="https://github.com/hako-mikan/sd-webui-regional-prompter/assets/139728478/24caf16b-8232-44a8-a775-922f5aca6b43">

<img width="682" alt="截屏2023-09-21 16 01 51" src="https://github.com/hako-mikan/sd-webui-regional-prompter/assets/139728478/5dba89c4-616b-44e8-bde5-6f33e5f3c381">

**And the result is:**

<img width="203" alt="截屏2023-09-21 15 54 17" src="https://github.com/hako-mikan/sd-webui-regional-prompter/assets/139728478/1e82c837-151f-4b02-9da7-493ff8e92a3a">

I'm confused if there is something wrong with my setting (I also tried other prompt types mentioned in your doc)

**Comment by LmaoLord** [comment]
as far as i know, in template field you don't write anything, it just tells you template to separate your regions in prompt field

**Comment by hako-mikan** [comment]
The Template serves an auxiliary role for what you input; the correct way to use it is to input what you have created with the Template into the prompt input field.
