### ISSUE TITLE
make the "visualize and make template" preview the same aspect ratio than the gen image

### ISSUE THREAD

**Issue by Hellrunner2k** [hako-mikan/sd-webui-regional-prompter#234]
this is the first thing that ppl ask when they start with regional prompter... can i see this over my picture? 

- so the preview window should be the same aspect ratio than the width/height of the generated image
- in img2img a 50/50 overlay with the input image would be really neat

this might be a minor change that does not affect the internal workings of the magic, might be undervalued, but would have a HUGE bump up in quality of the extension.

thx for your attention ... ^^

**Comment by hako-mikan** [comment]
For now, I have made it so that you can input the size of the template. Since it is difficult to automatically retrieve the size due to gradio's specifications, please input it. Regarding the overlay, I plan to implement it in due course.

**Comment by warrockmill** [comment]
Just to ask but in your screenshot you have an image in the background. Trying this on my Web UI I can't find any such preview. 
Is it there to provide an example of the ratio being applied or is there meant to be a background image in img2img/inpaint? Thanks.

**Comment by Ineman** [comment]
Does 'overlay ratio' do nothing at all in txt2img?
