### ISSUE TITLE
A bug in "2D region assignment" in "Rows mode" of "Matrix mode"

### ISSUE THREAD

**Issue by amichamich** [hako-mikan/sd-webui-regional-prompter#239]
The "Divide Ratio" of "1,1,1;1,2,1" in "Rows mode" of "Matrix mode" gives the following regions:

![rows](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/132435162/9614612c-a440-46c6-b103-a21e2e69226e)

I believe it is wrong and should be like:

![fix](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/132435162/e3d1771d-e743-49e9-9057-e3da2ad46198)

Note that the "Columns mode" works as expected for the same "Divide Ratio" as follows:

![columns](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/132435162/cc6db5b2-bb39-42aa-8d77-be4d925f56cb)

The issue is observed in the version of commit 029ecedd550b5d6899206786128895e5e452e34f

**Comment by hako-mikan** [comment]
Check `flip "," and ";"`
![test](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/122196982/640a14c0-c313-4bdf-b964-1c38f1fabc3e)

**Comment by amichamich** [comment]
Thank you for the fix!
