### ISSUE TITLE
Using 2 Character LoRA doesn't work

### ISSUE THREAD

**Issue by NTanker123** [hako-mikan/sd-webui-regional-prompter#240]
Hi, I'm trying to use Regional Prompter with 2 character LoRA, image generates 2 people but it keeps showing first LoRA character..

If I add more detail or add hair color, it still shows first character and changes only hair color

Is there some issue in SD 1.5.2 while using Regional Prompter?

**Comment by NightSkyFore** [comment]
I have the same problem too. And I fixed it by turning down sampling steps from 40 to 25. It seems that high steps would over rendering by first lora key, causing another character looking like the first one.

**Comment by NTanker123** [comment]
> I have the same problem too. And I fixed it by turning down sampling steps from 40 to 25. It seems that high steps would over rendering by first lora key, causing another character looking like the first one.

Interesting, I've tried on 28steps but didn't work

**Comment by NightSkyFore** [comment]
> > I have the same problem too. And I fixed it by turning down sampling steps from 40 to 25. It seems that high steps would over rendering by first lora key, causing another character looking like the first one.
> 
> Interesting, I've tried on 28steps but didn't work

Well, it only works in the case that I divide the matrix into '1,1' with sampling steps at 25.
When I try to generate a large wallpaper image and divide the matrix into '1;2,1,1', or any others of more than 3 regions, the problem occurs again, no matter at which steps. 
Now I have no idea to work with it. I think this would be a bug.

**Comment by hako-mikan** [comment]
Handling multiple LoRAs (Layers of Representation Adjustment) is very challenging. 
The method of training and the base model vary depending on the author of the LoRA, leading to various issues when segmenting the domain.
It's like dealing with realistic and illustrative models on the left and right sides, respectively, which causes various problems in the generation process. 
Ideally, LoRAs created by the same author using the same base model are less likely to have issues. 
Additionally, the effectiveness of tags like character names and appearances is crucial, and this too depends on how it was trained. 

Furthermore, Web-UI 1.5.2 is not recommended for use with LoRA as it has various problems.
