### ISSUE TITLE
RuntimeError: matl and mat2 shapes cannot be multiplied (77x2048 and 768x128）

### ISSUE THREAD

**Issue by yumianhuli1** [hako-mikan/sd-webui-regional-prompter#241]
When using the SDXL model and this plugin is checked, the title error is reported and can be run without checking

**Comment by hako-mikan** [comment]
Please try out this latest update.
Additionally, also give the newly added "Use LoHa or other" option a try.
If the issue persists, it would be helpful for a quicker resolution if you could provide details about the model and LoRA settings that are causing the same error.
