### ISSUE TITLE
AttributeError: 'Script' object has no attribute 'pt'

### ISSUE THREAD

**Issue by mmersky** [hako-mikan/sd-webui-regional-prompter#245]
Running latest version from repo with Automatic1111 on Macbook M1 Max. Issues occurs using attention generation mode. Latent mode works as expected. 

Prompt:

Dog ADDCOL
cat

Console error:

```
/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/attention.py", line 141, in matsepcalc
tll = self.pt if pn else self.nt
```

**Comment by hako-mikan** [comment]
If you have the error that says
`AttributeError: 'Options' object has no attribute 'lora_functional'`
before the error you written.
May be fixed.
