### ISSUE TITLE
Paid contract work for porting your regional prompter to a custom diffuers pipeline?

### ISSUE THREAD

**Issue by jrabek** [hako-mikan/sd-webui-regional-prompter#247]
@hako-mikan Apologies for making this an issue but I couldn't find a way to contact you directly.

Would you be open to paid contract work to port your approach to regional prompting to a diffusers pipeline?  Perfectly happy if you have it in your repo and open source it as well.

DM me on twitter if you are interested! https://twitter.com/jesserabek 🙏

**Comment by hako-mikan** [comment]
I am currently in the process of developing a pipeline. 
I have no intention of receiving payment for it. 
Do you have any requirements or requests regarding its implementation?
As of now, I am planning to implement the Attention mode for Col, Row, Prompt.

**Comment by jrabek** [comment]
Thanks for responding @hako-mikan !  We ended up implementing a more basic version for diffusers that only does vertical slices.  But would love to have the same level of functionality as your a1111 plugin but in diffusers.

The biggest change we made from your original approach was allowing for per region positive *and* negative prompts for when we have two characters in the same image that each require their own negative prompts to look correct.

In general we found the latent mode to be slower and not work as well and attention mode in terms of quality.

We would be happy to test the diffusers version when it comes out 🙏

**Comment by jrabek** [comment]
Closing this issue since you are already working on this 🦾

**Comment by hako-mikan** [comment]
Ah. In my script, it is possible to specify negative prompts for each region. 
If there is no specification to divide, the same prompt will be applied though.

**Comment by hako-mikan** [comment]
I submitted a pull request.
https://github.com/huggingface/diffusers/pull/6015

**Comment by Bochu3** [comment]
I want to say thank you. I waited regional prompt in diffusers for long time. 
I tried RegionalPromptingStableDiffusionPipeline. Cols and Rows work fine while it returns error using Prompt mode.
`UnboundLocalError: local variable 'reshaped' referenced before assignment` in line 330

**Comment by jrabek** [comment]
This is super cool!  Awesome job!
