### ISSUE TITLE
AttributeError: 'Script' object has no attribute 'pt', Error running process, Error running postprocess

### ISSUE THREAD

**Issue by z-p-a-i** [hako-mikan/sd-webui-regional-prompter#248]
Hi, i am using Automatic1111 v1.6.0 with git pull update, on windows 11, Nvidia RTX4070.

I face problem using Regional Prompter extension. when generate in Attention mode, it fails to generate image and return this AttributeError: 'Script' object has no attribute 'pt'. Just as below:

![Screenshot 2023-10-10 141645](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/147476960/96e4099e-b3df-4b16-be47-ccc7bd8ee36e)

Details of error:
1. Starts the WebUI as usual. then i see this error. but i could generate image as usual.

> *** Error running process: C:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
...

2. In RP extension, press Active. Attention mode. Divide ratio 1,1. then in positive prompt, 

> dog and cat

returns a dog and a cat. but whenever add BREAK command, 

> dog and BREAK cat

returns the above AttributeError. the full command log as below:

> 1,1 0.2 Horizontal
> *** Error running process: C:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py
>     Traceback (most recent call last):
>       File "C:\stable-diffusion-webui\modules\scripts.py", line 619, in process
>         script.process(p, *script_args)
>       File "C:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 462, in process
>         unloadlorafowards(p)
>       File "C:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\latent.py", line 571, in unloadlorafowards
>         shared.opts.lora_functional =  orig_lora_functional
>       File "C:\stable-diffusion-webui\modules\options.py", line 91, in __setattr__
>         if info.do_not_save:
>     AttributeError: 'NoneType' object has no attribute 'do_not_save'---
> 
>   0%|                                                                                           | 0/20 [00:00<?, ?it/s]
> *** Error completing request
> *** Arguments: ('task(0xdqdhx6zo2o77a)', 'dog and BREAK cat', '', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000001F396FD9AE0>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, True, False, 'Matrix', 'Columns', 'Mask', 'Prompt', '1,1', '0.2', False, False, False, 'Attention', False, '0', '0', '0.4', None, '0', '0', False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False, [], 30, '', 4, [], 1, '', '', '', '') {}
>     Traceback (most recent call last):
>       File "C:\stable-diffusion-webui\modules\call_queue.py", line 57, in f
>         res = list(func(*args, **kwargs))
>       File "C:\stable-diffusion-webui\modules\call_queue.py", line 36, in f
>         res = func(*args, **kwargs)
>       File "C:\stable-diffusion-webui\modules\txt2img.py", line 55, in txt2img
>         processed = processing.process_images(p)
>       File "C:\stable-diffusion-webui\modules\processing.py", line 732, in process_images
>         res = process_images_inner(p)
>       File "C:\stable-diffusion-webui\modules\processing.py", line 867, in process_images_inner
>         samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
>       File "C:\stable-diffusion-webui\modules\processing.py", line 1140, in sample
>         samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
>       File "C:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in sample
>         samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
>       File "C:\stable-diffusion-webui\modules\sd_samplers_common.py", line 261, in launch_sampling
>         return func()
>       File "C:\stable-diffusion-webui\modules\sd_samplers_kdiffusion.py", line 235, in <lambda>
>         samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
>       File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
>         return func(*args, **kwargs)
>       File "C:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
>         denoised = model(x, sigmas[i] * s_in, **extra_args)
>       File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>         return forward_call(*args, **kwargs)
>       File "C:\stable-diffusion-webui\modules\sd_samplers_cfg_denoiser.py", line 188, in forward
>         x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
>       File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>         return forward_call(*args, **kwargs)
>       File "C:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
>         eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
>       File "C:\stable-diffusion-webui\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
>         return self.inner_model.apply_model(*args, **kwargs)
>       File "C:\stable-diffusion-webui\modules\sd_hijack_utils.py", line 17, in <lambda>
>         setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
>       File "C:\stable-diffusion-webui\modules\sd_hijack_utils.py", line 28, in __call__
>         return self.__orig_func(*args, **kwargs)
>       File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
>         x_recon = self.model(x_noisy, t, **cond)
>       File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
>         result = forward_call(*args, **kwargs)
>       File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
>         out = self.diffusion_model(x, t, context=cc)
>       File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>         return forward_call(*args, **kwargs)
>       File "C:\stable-diffusion-webui\modules\sd_unet.py", line 91, in UNetModel_forward
>         return ldm.modules.diffusionmodules.openaimodel.copy_of_UNetModel_forward_for_webui(self, x, timesteps, context, *args, **kwargs)
>       File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
>         h = module(h, emb, context)
>       File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>         return forward_call(*args, **kwargs)
>       File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
>         x = layer(x, context)
>       File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>         return forward_call(*args, **kwargs)
>       File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
>         x = block(x, context=context[i])
>       File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>         return forward_call(*args, **kwargs)
>       File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
>         return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
>       File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
>         return CheckpointFunction.apply(func, len(inputs), *args)
>       File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
>         return super().apply(*args, **kwargs)  # type: ignore[misc]
>       File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
>         output_tensors = ctx.run_function(*ctx.input_tensors)
>       File "C:\stable-diffusion-webui\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 273, in _forward
>         x = self.attn2(self.norm2(x), context=context) + x
>       File "C:\stable-diffusion-webui\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>         return forward_call(*args, **kwargs)
>       File "C:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 397, in forward
>         ox = matsepcalc(x, contexts, mask, True, 1)
>       File "C:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\attention.py", line 141, in matsepcalc
>         tll = self.pt if pn else self.nt
>     AttributeError: 'Script' object has no attribute 'pt'
> 
> ---

3. Fresh reinstall RP, and/or disable all other extension, or even delete the venv and repositories folders, could not solve it, comes the same error.
4. Surprisingly, when i switch to Latent mode, or under Script - Differential Regional Prompter (but i dont know what this is), i am able to generate image, but i hardly got decent image and RP seems no effect.

Please help me, i am stuck and have gone thru your Closed issues, got no solution, and I am zero about programming,
Thank you.

**Comment by LankyPoet** [comment]
I have a similar problem. Using SDXL in SD.NEXT, I receive the following:
`[1] [[1.0, 1.0, 1.0]]
1,1,1 0 Horizontal
14:26:42-055441 ERROR    Running script process: extensions\sd-webui-regional-prompter\scripts\rp.py: AttributeError
╭──────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────╮│ C:\sdnext\modules\scripts.py:470 in process                                                                                       ││                                                                                                                                   ││   469 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                                    ││ ❱ 470 │   │   │   │   script.process(p, *args, **kwargs)                                                                          ││   471 │   │   │   except Exception as e:                                                                                          ││                                                                                                                                   ││ C:\sdnext\extensions\sd-webui-regional-prompter\scripts\rp.py:464 in process                                                      ││                                                                                                                                   ││    463 │   │   │   else:                                                                                                          ││ ❱  464 │   │   │   │   self.handle = hook_forwards(self, p.sd_model.model.diffusion_model,remov                                   ││    465 │   │   │   │   setuploras(self)                                                                                           ││                                                                                                                                   ││ C:\sdnext\venv\lib\site-packages\diffusers\configuration_utils.py:137 in __getattr__                                              ││                                                                                                                                   ││   136 │   │                                                                                                                       ││ ❱ 137 │   │   raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'"                                    ││   138                                                                                                                             │╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯AttributeError: 'StableDiffusionXLPipeline' object has no attribute 'model'
14:26:43-977454 STATUS   LoRA loaded: Homelander1024-000126 strength=0.4 loader="sequential apply" lora=1.81s
14:26:46-681497 STATUS   LoRA loaded: Henry_Cornswet-Henry_Cavill strength=1.5 loader="sequential apply" lora=2.69s
14:26:46-709225 ERROR    Running script process batch: extensions\sd-webui-regional-prompter\scripts\rp.py: AttributeError
╭──────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────╮│ C:\sdnext\modules\scripts.py:492 in process_batch                                                                                 ││                                                                                                                                   ││   491 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                                    ││ ❱ 492 │   │   │   │   script.process_batch(p, *args, **kwargs)                                                                    ││   493 │   │   │   except Exception as e:                                                                                          ││                                                                                                                                   ││ C:\sdnext\extensions\sd-webui-regional-prompter\scripts\rp.py:534 in process_batch                                                ││                                                                                                                                   ││    533 │   │   │   │   else:                                                                                                      ││ ❱  534 │   │   │   │   │   restoremodel(p)                                                                                        ││    535 │   │   │   │   │   denoiserdealer(self)                                                                                   ││                                                                                                                                   ││ C:\sdnext\extensions\sd-webui-regional-prompter\scripts\latent.py:557 in restoremodel                                             ││                                                                                                                                   ││   556 │   model = p.sd_model                                                                                                      ││ ❱ 557 │   for name, module in model.named_modules():                                                                              ││   558 │   │   if hasattr(module, "lora_weights_backup"):                                                                          ││                                                                                                                                   ││ C:\sdnext\venv\lib\site-packages\diffusers\configuration_utils.py:137 in __getattr__                                              ││                                                                                                                                   ││   136 │   │                                                                                                                       ││ ❱ 137 │   │   raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'"                                    ││   138                                                                                                                             │╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯AttributeError: 'StableDiffusionXLPipeline' object has no attribute 'named_modules'`

**Comment by hako-mikan** [comment]
probably fixed

**Comment by titlestad** [comment]
Not fixed. Latest everything. Need to use Latent (which doesn't seem to do anything).

File "/media/xxx/Projects/stable-diffusion-webui-forge/extensions/sd-forge-regional-prompter/scripts/attention.py", line 420, in forward
    ox = matsepcalc(x, contexts, mask, True, 1)
  File "/media/xxx/Projects/stable-diffusion-webui-forge/extensions/sd-forge-regional-prompter/scripts/attention.py", line 163, in matsepcalc
    tll = self.pt if pn else self.nt
AttributeError: 'Script' object has no attribute 'pt'
'Script' object has no attribute 'pt'

**Comment by yukitokog** [comment]
Still the same. Works for Automatic1111, doesn't work for Forge. Common directory for both. Works only by switching to Latent.
