### ISSUE TITLE
Prompt manipulation causes second section to be lost

### ISSUE THREAD

**Issue by Seshelle** [hako-mikan/sd-webui-regional-prompter#249]
The following prompt causes the second section of the prompt to be lost, rather than beings split into two sections. This is done with default settings (no base or common prompts and a 1,1 horizontal split)

![02780-257825397](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/13323032/709270c6-6d7b-4514-913e-e212aba41eba)

`Duo, human, pants, t-shirt, bright forest background, [digital drawing \(artwork\):digital media \(artwork\):.2], [ traditional media \(artwork\)::3d \(artwork\):.2], full-length portrait, front view, three-quarter view, masterpiece, best quality, hi res, black hair, ababa, dabad, 
delete-this
BREAK
Duo, human, pants, t-shirt, bright forest background, [digital drawing \(artwork\):digital media \(artwork\):.2], [ traditional media \(artwork\)::3d \(artwork\):.2], full-length portrait, front view, three-quarter view, masterpiece, best quality, hi res, black hair, ababa, dabad, 
delete-this`

It seems the error occurs because Regional Prompt Extension estimates the first prompt contains 78 token, while A1111 measures it as 68 tokens. I believe this is causing it to overestimate the number of BREAKs in the prompt and ignore the last section. If you delete the "delete-this" from the the sections, the sections work properly again. This is presumably because the extension now correctly estimates the prompt to be less than 75 tokens.

![02781-1740906767](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/13323032/9f4f9247-bc79-49b6-829b-d8c50a7cc609)

**Comment by hako-mikan** [comment]
Fixed.
