### ISSUE TITLE
How to solve the mutual influence of 2 LORAs in Latent mode？

### ISSUE THREAD

**Issue by Orihane** [hako-mikan/sd-webui-regional-prompter#25]
Sorry, I think my English expression ability may not be able to express clearly, so I chose to use Google Translate.
Thanks for sharing this plugin, it's great! But I got a little problem when using.
I see the sample image you posted in the intro works great,but I try to generate some pictures, lora always affect each other.
I can't make a picture like the two hatsune in the example picture.
So,can you give me a case study for reference?
In addition, I originally wanted to enable 'Composable LoRA' to solve this problem, but it seems that the two may have compatibility issues.

**Comment by hako-mikan** [comment]
Yeah, it is hard to handle multiple LoRAs.
In case of multiple LoRAs, affect each other.
So you need to suppress the effect.
here is the sample.
```
2girls shakehand, full-body,miku hatsune, ADDCOMM
<lora:nendoroidFIGURESLora_v10:0.5:1,0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0>ADDCOL
FIGMA <lora:figmaAnimeFigures_figma:0.4:1,0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0> 
```
`1,0,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0` is setting for LoRA block weight script.
By using this script you can reduce unnecessary effects of LoRAs.
https://github.com/hako-mikan/sd-webui-lora-block-weight

**Comment by Orihane** [comment]
thanks a lot,I'll try more.
