### ISSUE TITLE
"Prompt" or "Prompt-EX" in Automatic1111 using Hires Fix fails

### ISSUE THREAD

**Issue by Kalatz777** [hako-mikan/sd-webui-regional-prompter#250]
Using Hires Fix with either "Prompt" or "Prompt-EX" in Automatic1111, keeps failing with the below error:
RuntimeError: shape '[10, 16128]' is invalid for input of size 129024

If I turn off hires Fix or use another tab, ie Matrix or Mask, they work fine with Hires Fix.

**Comment by hako-mikan** [comment]
Fixed.
This error occurs "When a value that is not a multiple of 8 is input into hires size.
What value did you enter?

**Comment by Kalatz777** [comment]
Great thank you.
I tried using both 1024 x 1024 and 1088 x 960 for SDXL models.
