### ISSUE TITLE
AttributeError: 'StableDiffusionXLPipeline' object has no attribute 'model'

### ISSUE THREAD

**Issue by LankyPoet** [hako-mikan/sd-webui-regional-prompter#254]
When running the newest Regional Prompter (8d96c92) with the newest SD.NEXT (53d0cb3), I receive the following error in the log no matter which options I select:

`19:29:45-332788 ERROR    Running script process: extensions\sd-webui-regional-prompter\scripts\rp.py: AttributeError
╭──────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────╮
│ C:\sdnext\modules\scripts.py:471 in process                                                                                       │
│                                                                                                                                   │
│   470 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                                    │
│ ❱ 471 │   │   │   │   script.process(p, *args, **kwargs)                                                                          │
│   472 │   │   │   except Exception as e:                                                                                          │
│                                                                                                                                   │
│ C:\sdnext\extensions\sd-webui-regional-prompter\scripts\rp.py:480 in process                                                      │
│                                                                                                                                   │
│    479 │   │   │   if "Att" in calcmode:                                                                                          │
│ ❱  480 │   │   │   │   self.handle = hook_forwards(self, p.sd_model.model.diffusion_model)                                        │
│    481 │   │   │   │   if hasattr(shared.opts,"batch_cond_uncond"):                                                               │
│                                                                                                                                   │
│ C:\sdnext\venv\lib\site-packages\diffusers\configuration_utils.py:137 in __getattr__                                              │
│                                                                                                                                   │
│   136 │   │                                                                                                                       │
│ ❱ 137 │   │   raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'"                                    │
│   138                                                                                                                             │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'StableDiffusionXLPipeline' object has no attribute 'model'`

I am running:
19:22:33-725937 INFO     Version: app=sd.next updated=2023-10-19 hash=53d0cb35
                         url=https://github.com/vladmandic/automatic.git/tree/master
on Windows 11, using Firefox. I was not using loras, just using SDXL model and following the samples in the Usage guide of the Readme.

**Comment by hako-mikan** [comment]
The `StableDiffusionXLPipeline` is a method introduced by `SD.Next` for XL models, but it is not compatible with the Regional Prompter. If you want to use SDXL, Use A1111 Web-UI.

**Comment by LankyPoet** [comment]
Awww what a shame. I know the author of SD.Next added a compatibility layer for some other extensions so I will raise this issue there as well. Thank you!

**Comment by 15091444119** [comment]
Hi， I fail to use sdxl in the diffuser pipeline Regional Prompting Pipeline, err code is

**Comment by 15091444119** [comment]
Hi, I fail to use sdxl model in regional prompt diffuser pipeline, will you implement a sdxl  version ?
