### ISSUE TITLE
Embedding won't unload for the new bundle format when regional prompter is enabled

### ISSUE THREAD

**Issue by cyber-meow** [hako-mikan/sd-webui-regional-prompter#258]
**Describe the bug**

A bundle format is recently added to the dev branch of webui: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/13568 (for an example file see https://civitai.com/models/173081/)
This can be regarded as a LoRA with multiples built-in embeddings and is particularly relevant for the case of pivotal tuning (training of both LoRAs and embeddings together): https://civitai.com/articles/2494/making-better-loras-with-pivotal-tuning

The normal behavior is that the embeddings are only loaded when the LoRA is used, and otherwise gets unloaded afterwards 
![image](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/24396911/bdcbe0d0-1fe2-4f23-9d89-011fccc28a58)

Yet, when regional prompter is enabled, the embeddings are never unloaded. For example, I can get such warning which should only occur when embeddings already exist.
![Screenshot from 2023-10-22 13-33-38](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/24396911/5b3199c0-1e54-4a3d-9776-fd570b65630a)

The embeddings continue to take effect even if I remove the lora. I guess this is related to how LoRA is loaded in regional prompter.

**Environment**
Web-UI version: dev commit 464fbcd9
SD Version: 1.5

**Other Enabled Extensions**
I can observe this behavior when only built-in extensions and regional prompter are enabled.

**Comment by hako-mikan** [comment]
Fixed.
