### ISSUE TITLE
AttributeError: module 'networks' has no attribute 'originals'

### ISSUE THREAD

**Issue by gekisilver** [hako-mikan/sd-webui-regional-prompter#259]
hi whenever i try using ''latent'' it gives me the ''AttributeError: module 'networks' has no attribute 'originals' 
![imagen_2023-10-23_203357189](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/148807252/265a9f60-6efc-43d4-b60b-7d26190cc9ef)

**Comment by hako-mikan** [comment]
Tell me what kind of LoRA you use.

**Comment by gekisilver** [comment]
> Tell me what kind of LoRA you use.

The error appears even when i'm not using a lora, it happens when i choose LATENT instead of attention

but im using these two https://civitai.com/models/169332/pneuma-xenoblade-chronicles-2
https://civitai.com/models/171483/tsukuyomi-shirabe-senki-zesshou-symphogear

**Comment by zemooo7** [comment]
Me too, attention mode can works fine, but latent mode gives the same error (not using LoRA).
Here's my args:

`{"batch_size":1,"seed":-1,"n_iter":1,"steps":55,"negative_prompt":"overexposed,colour supersaturation,obscure,blur,foggy,complex,people,ugly, text,logo,noisy point,dark,black. BREAK complex , many elements BREAK","denoising_strength":0.8,"width":1920,"sampler_index":"Euler a","hr_upscaler":"R-ESRGAN 4x+ Anime6B","alwayson_scripts":{"Adetailer":{"args":[true,{"ad_model":"face_yolov8n.pt"}]},"Regional Prompter":{"args":["True","False","Matrix","Vertical","Mask","Prompt","1,2","","False","True","True","Latent","False","0","0","0",""]}},"prompt":"ultra simple illustration of a boat on the island in the rain, the sound of the boat and the rain intertwine, boat, rain curtain, deck, ocean, youthful, ambience, concept art, beautiful color scheme, fine detail, sharp edges, high quality, masterwork, wlop, Sylvain Sarrailh, wide composition, digital art,8k, best quality,unreal engine. 1 BREAK BREAK","cfg_scale":7,"height":234,"enable_hr":true}`

**Comment by 39kir** [comment]
Me too. In my environment, it occurs when I type "AND" or "BREAK" in Latent.
version: [v1.5.1] python: 3.10.8  •  torch: 2.0.1+cu118  •  xformers: N/A  •  gradio: 3.32.0
