### ISSUE TITLE
Preserve settings when sending with "Send to img2img"

### ISSUE THREAD

**Issue by space-nuko** [hako-mikan/sd-webui-regional-prompter#26]
Would be nice if settings were copied to the img2img tab. Could use the `infotext_fields` and `paste_field_names` of the `Script` class to accomplish this

**Comment by matrix4767** [comment]
Agreed and for the same to apply to reading generation parameters from prompt button.

**Comment by hako-mikan** [comment]
Thanks for telling `infotext_fields` and `paste_field_names`.
I added that feature.
