### ISSUE TITLE
I feel like the speed on image generation with Latent is way slower than a few months ago 

### ISSUE THREAD

**Issue by Kamekos** [hako-mikan/sd-webui-regional-prompter#261]
Anyone is facing a similar issue ? It's taking me thrice as much time as before to generate a single image with the Latent mode

**Comment by hako-mikan** [comment]
Are you using LoRA? If you are using LoRA, it's inevitable that the process is slower.
This is due to changes in the specifications related to LoRA in the Web-UI.
