### ISSUE TITLE
regional prompter failure 

### ISSUE THREAD

**Issue by joindn** [hako-mikan/sd-webui-regional-prompter#271]
**Describe the bug**
In some cases, there is an issue with the failure of prompt word partitioning. For instance, consider the meta information below an image: How can this situation be resolve

**Environment**
Web-UI version: 1.6
SD Version: 1.5
meta: 
best quality,masterpiece,2persons,(Point of View:1.5),(Full Shot:1.5),Women,pregnant,touching their stomachs,men,the woman is pregnant,feeling her belly,and next to her stands a man in a suit,(realistic:1.2),(dramatic lighting:1.1),(vivid color palette:1.2),(illustration:0.7),(modern art style:0.8),(expressive character design:1.1),(cinematic composition:0.9)BREAK 1 woman,pregnant,BREAK 1 man,dress in a black suit,
Negative prompt: DeepNegative,EasyNegative,bad anatomy,bad body,bad feet,bad hands,bad proportions,bad-hands-5,bad_prompt_version2,deformed,error,extra arms,extra digit,extra fingers,extra foot,extra leg,extra legs,extra limbs,fewer digits,fused fingers,gross proportions,jpegartifacts,logo,low quality,lowres,malformed limbs,missing arms,missing fingers,missing legs,morbid,mutated hands,mutation,ng_deepnegative_v1_75t,normal quality,nsfw,polar lowres,poorly drawn face,poorly drawn hands,repeating hair,signature,sketches,text,tilted head,too many fingers,ugly face,username,verybadimagenegative_v1.3,watermark,worst quality,worstquality,DeepNegative,monochrome,cropped,jpeg artifacts,
Steps: 30, Sampler: Restart, CFG scale: 7, Seed: 1325182964, Size: 768x512, Model hash: 0f5b5d7b9c, VAE hash: 235745af8d, Clip skip: 2, Style Selector Enabled: True, Style Selector Randomize: False, Style Selector Style: base, RP Active: True, RP Divide mode: Matrix, RP Matrix submode: Columns, RP Mask submode: Mask, RP Prompt submode: Prompt, RP Calc Mode: Attention, RP Ratios: "1,1", RP Base Ratios: 0.2, RP Use Base: False, RP Use Common: True, RP Use Ncommon: False, RP Options: [False], RP LoRA Neg Te Ratios: 0, RP LoRA Neg U Ratios: 0, RP threshold: 0.4, RP LoRA Stop Step: 0, RP LoRA Hires Stop Step: 0, RP Flip: False, TI hashes: "EasyNegative: 66a7279a88dd, bad-hands-5: aa7651be154c, bad_prompt_version2: 6f35e7dd816a, ng_deepnegative_v1_75t: 54e7e4826d53, verybadimagenegative_v1.3: d70463f87042", Pad conds: True, Version: v1.6.0

**Comment by hako-mikan** [comment]
There was a bug related to using long negative prompts, which has been fixed. Additionally, there is room for improvement in the prompts you are using. Common prompts should only include general instructions. The part `Women, pregnant, touching their stomachs, men, the woman is pregnant,` should not be included in the common prompt. If it's included in the common, she will appear in both areas.
