### ISSUE TITLE
UI is broken with Vladmandic's SD NEXT t2i

### ISSUE THREAD

**Issue by ashdarain** [hako-mikan/sd-webui-regional-prompter#275]
**Describe the bug**
Using a fresh install of SD Next, whenever the UI updates, it unchecks any of the selected options. Updated the UI at all in t2i (switch to mask mode, hitting generate, typing in a field etc.) unchecks any of the radio buttons (columns/rows, attention/latent, marks, etc.)

Weird thing is this extension still works, just UI gets all messed up

**Environment**
Web-UI version: fresh install of Update for 2023-11-23

**Other Enabled Extensions**
- a1111-sd-webui-tagcomplete
- sd-dynamic-prompts
- sd-webui-pixelart

**Comment by hako-mikan** [comment]
GPT

I've installed and tested the latest version of SD.Next, and it seems to be working properly. I haven't encountered such issues with other Web-UI forks either, so if there are any problems, they're likely specific to SD.Next. It would probably be faster to report them directly to the creator of SD.Next.
