### ISSUE TITLE
Error Executing callback cfg_denoised_callback

### ISSUE THREAD

**Issue by LizardKing777** [hako-mikan/sd-webui-regional-prompter#280]
I can't get Latent to work at all. Every time I try to use it I get this error each iteration:

```
*** Error executing callback cfg_denoised_callback for /home/lizard/Downloads/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py
    Traceback (most recent call last):
      File "/home/lizard/Downloads/stable-diffusion-webui/modules/script_callbacks.py", line 224, in cfg_denoised_callback
        c.callback(params)
      File "/home/lizard/Downloads/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/rp.py", line 591, in denoised_callback
        denoised_callback_s(self, params)
      File "/home/lizard/Downloads/stable-diffusion-webui/extensions/sd-webui-regional-prompter/scripts/latent.py", line 194, in denoised_callback_s
        fil = self.filters[a + b*areas]
    IndexError: list index out of range
```

I get the same error when using LORAs in the prompt or using the Lora Mask extension. Same error when using Dynamic Lora Masks, Lora Block Weight and Composable Lora. 

I even get the problem with a blank prompt and no LORAs active at all.

**Environment**

OS: Ubuntu 22.04
Web-UI version:  Just updated to latest version
SD Version: 1.5
LoRA/LoCon/LoHa: All not working

**Other Enabled Extensions**

Dynamic Prompts (doesn't work whether active or not)
Dynamic Thresholding (doesn't work whether active or not)
Lora Masks (doesn't work whether active or not)
NegPip (doesn't work whether active or not)

**Comment by LizardKing777** [comment]
Also when using NegativePiP it doesn't appear to pick up anything written as (Word:-1.5) - in the cli it says : "NegPiP enable, Positive:None,Negative:None"

**Comment by hako-mikan** [comment]
This error often occurs when the number of specified BREAKs does not match the number of specified areas. Does this also happen even in a simple 1:1 area?

**Comment by Adlaran** [comment]
I faced absolutely same error trying use masks with latent mode. 
Error disappears only if I remove all BREAKs from the prompt, but it obvious does not help to use regions.
