### ISSUE TITLE
¿Example prompt to 2 characters?

### ISSUE THREAD

**Issue by qa-breveloper** [hako-mikan/sd-webui-regional-prompter#281]
Hello, I'm testing this extension and it looks very interesting. I have a question: I want to make a prompt with two different girls, but I don't think the internet tutorials explain this well.

In my case, I think I am going to activate ADDCOMM, but if you think it is better to use ADDBASE, please enlighten me.

I would be:

2girls ADDCOMM masterpiece, 8k, street ADDCOL japanese girl, dress, shoes, hat, ADDCOL african girl, dress, twintails, shoes, bag

![imagen](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/132348671/196ea310-c381-465f-95b3-659600bbbaaf)

Or do I use BREAK to separate them?

![imagen](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/132348671/f679b745-da79-440b-a483-5faedaa3cbc8)

My config:

![imagen](https://github.com/hako-mikan/sd-webui-regional-prompter/assets/132348671/9830461a-0c24-4d14-8f12-f78dc44b89d0)

Thanks!

**Comment by blugail** [comment]
You use break if you want to use the regions as they are in the preview, and ADDCOM and ADDCOL if you want to specify the regions in the prompt.

Generally you use common prompts for describing the group: "2 girls walking down the street"
and Columns for describing an individual member "an African girl"

I've had bad luck trying to put styles in the common prompt. For some reason they never take, and I have to add them to the individual parts. I think It would work much better if there was a "common post" and a "common pre" prompt.

**Comment by hako-mikan** [comment]
It would be better to do it as follows:
```
2girls masterpiece, 8k, street ADDCOMM Japanese girl, dress, shoes, hat, ADDCOL African girl, dress, twintails, shoes, bag
```
What you want to do is to split the screen into two and display different girls on the left and right sides. The prompt entered before ADDCOMM will be applied to all areas, so with the prompt you entered, it would result in specifying three areas as follows:

```
2girls, masterpiece, 8k, street ADDCOL 
2girls, Japanese girl, dress, shoes, hat, ADDCOL 
2girls, African girl, dress, twintails, shoes, bag
```
However, with:
```
2girls masterpiece, 8k, street ADDCOMM Japanese girl, dress, shoes, hat, ADDCOL African girl, dress, twintails, shoes, bag
```
It would result in:
```
2girls masterpiece, 8k, street Japanese girl, dress, shoes, hat ADDCOL 
2girls masterpiece, African girl, dress, twintails, shoes, bag
```

**Comment by hako-mikan** [comment]
@blugail 
That's good idea. Thanks.

**Comment by qa-breveloper** [comment]
Thanks!
