### ISSUE TITLE
Option to ignore or change BREAK as regional keyword?

### ISSUE THREAD

**Issue by AG-w** [hako-mikan/sd-webui-regional-prompter#286]
The original function of BREAK is to split up prompts into chunk, you can use it to prevent prompt mix into each other

This extension use BREAK as a keyword to break up region, but I'm already using BREAK in prompts to control the object in picture.
The result is image layout mixed up even if I use special separator ADDCOL/ADDROW from this extension

is it possible to make it an option to stop BREAK as regional keyword?

**Comment by hako-mikan** [comment]
Added Option "Use BREAK to change chunks".
