### ISSUE TITLE
May I ask if the regional prompt can also achieve good control in img2img?

### ISSUE THREAD

**Issue by lu2022start** [hako-mikan/sd-webui-regional-prompter#304]
May I ask if the regional prompt can also achieve good control in img2img?

**Comment by Heather95** [comment]
Yes. Why were you unable to verify this yourself? No offense, but the issue feature on GitHub is not intended to be used for general questions.

**Comment by Heather95** [comment]
@FIR2022start I apologize about my wording. I realize not everyone is aware of the Discussions tab. Please try to use it in the future. https://github.com/hako-mikan/sd-webui-regional-prompter/discussions

[Here are some advanced instructions](https://www.reddit.com/r/StableDiffusion/comments/189ypyu/comment/kbv0f78/) about how to use Regional Prompter in img2img, taken from a Reddit user.


`Regional prompting, turn it on. Click on the 2nd option for masking. Load the photo into regional prompting. Then draw a mask over the first subject, click the apply mask button.. Then scroll back to the top and in your prompt describe what is under the mask, when finished end the line with BREAK. Hit enter so are now on a new line.`

`Then draw the next mask, again describe what's under the mask, end with BREAK. Hit enter to again go to the next line. Scroll back down to regional prompting.`

`Rinse and repeat until you are finished.`

`That is the gist of regional prompting with masking.`

`If you don't see a mask drawn in different colors you are clicking the wrong button, there are two options.`

`When completely done, hit generate.`

`If you choose one of the options for generic prompt, you need to enter that information in before your first mask line and end with a BREAK.`

`Example: Five people, smiling, in photo, BREAK Tall guy, blonde hair, blue eyes, BREAK (corresponds to lowest number mask) Short girl, blue hair, red eyes, BREAK Etc.`

`You could also add in control net, to further lock in the original image.`

**Comment by FIR2022start** [comment]
Thank you very much and I apologize for the overly general question. I indeed did not know how to use the Discussions tab before, but I will look there for the information I need in the future. Additionally, thank you for providing the reference answer!
