### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by sicafoose** [hako-mikan/sd-webui-regional-prompter#311]
**As the title states**
So I've been trying to use this extension and will generate an image as long as I don't use ADDCOL, ADDCOMM, BREAK, ADDBASE. The minute I use those commands I get the TypeError: 'NoneType' object is not iterable. If there is a fix for this, please explain like im 13 to resolve this issue.

**Environment**
Web-UI version: FORGE
SD Version: SDXL

**Other Enabled Extensions**
NONE

**Comment by Heather95** [comment]
Already tracked issue duplicate #307 
The solution [is here](https://github.com/hako-mikan/sd-webui-regional-prompter/issues/307#issuecomment-2026438373)
