### ISSUE TITLE
NegPip not recognizing keywords after BREAK

### ISSUE THREAD

**Issue by LizardKing777** [hako-mikan/sd-webui-regional-prompter#313]
Negative Prompt in Prompt only picks up the negative keywords in the initial prompt. It does seem to pick up the Base prompt but isn't registering any keywords after that.

Example prompt:
```
A lizardman and a woman standing in a swamp (worst quality:-1.2)
BREAK <----- ***stops recognizing negative keywords here.***
Swamp, (snakes:-1.2)
BREAK
A redhaired woman in plate armour, (child:-1.2), (loli:-1.2)
BREAK     
A lizardman carrying a spear (human:-1.2)
```

OS: Ubuntu 22.04
Web-UI version: Just updated to latest version
SD Version: 1.5
LoRA/LoCon/LoHa: All not working

Other Enabled Extensions

Dynamic Prompts (doesn't work whether active or not)
Dynamic Thresholding (doesn't work whether active or not)
Lora Masks (doesn't work whether active or not)
NegPip (doesn't work whether active or not)

**Comment by hako-mikan** [comment]
From my tests, it's working fine. Try the following:

    Use COMMON instead of BASE. Using BASE weakens the effect by its ratio.
    Increase the negative weights.
    Turn off NegPiP. If it really doesn't have an effect, negatives will be treated as positives, resulting in a completely different image.
