### ISSUE TITLE
How Attention mode keep the partition？

### ISSUE THREAD

**Issue by Saintafox** [hako-mikan/sd-webui-regional-prompter#314]
I am quite confused about the main theory of the Attention mode, on the way it keeps the partition. 

For Latent mode, it uses 2 sets of separated prompts, and generate 2 sides of the picture, then combine them with the basic prompts' output, then make the final output.

But for Attention mode, seems it quite focus more on the efficiency of generating process in UNet units, on K,V not Q. But I still don't understand the way it maintain the independence of the generated images on the left and right sides, does it use the same way like Latent mode do(generate separately, after which the weighted sum)? 

Thank you so much for describing！

**Comment by hako-mikan** [comment]
Yes. It's the same as latent mode. 
The same process as in latent mode is performed during each CrossAttention calculation.
