### ISSUE TITLE
Latent mode using 2 Lora ->after-> Regional Prompter Disabled -> using 1 Lora ->Error

### ISSUE THREAD

**Issue by freebag668** [hako-mikan/sd-webui-regional-prompter#32]
https://postimg.cc/LhS1pmxj
Latent mode using 2 Lora
it goes well

https://postimg.cc/K34KH85T
https://postimg.cc/MnYW187J
https://postimg.cc/4mQCSQmz
https://postimg.cc/V54p9LTR
Regional Prompter Disabled
using 1 Lora
Error

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_mm)
A message pops up with an error

https://postimg.cc/gXxXM0sZ
525741c0 (Wed Apr 5 10:33:35 2023)
regional-prompter
All extensions are up to date

Could it be solved?

Thank you for your hard work as always

**Comment by Symbiomatrix** [comment]
So if I understand correctly:
1) You activated regional, with latent mode, 2 loras, and batch count of 5.
2) You deactivated regional mode, and now every setting (with batch 5) fails.

First, have you tried reducing batch from 5 to 1 with regional disabled?
Theoretically, when regional is inactive it's not supposed to raise any errors whatsoever. Glancing over the code, I think that either the unloader is missing a certain property (lora), or in batch mode the deactivation isn't operating cleanly - I see several types of flag checks (self, parameter, global lactive), something could have gone wrong there.

**Comment by freebag668** [comment]
> 그래서 내가 올바르게 이해한다면 :
> 
> 1. 잠재 모드, 2 loras 및 배치 수 5로 지역을 활성화했습니다.
> 2. 지역 모드를 비활성화하고 이제 모든 설정(배치 5 포함)이 실패합니다(또는 일부 lora가 활성화된 경우입니까?).
> 
> 먼저, 지역 비활성화로 배치를 5에서 1로 줄이려고 했습니까? 이론적으로 지역이 비활성 상태이면 어떤 오류도 발생하지 않습니다. 코드를 살펴보면 언로더에 특정 속성(lora)이 없거나 배치 모드에서 비활성화가 제대로 작동하지 않는 것 같습니다. 여러 유형의 플래그 검사(self, parameter, global lactive)를 볼 수 있습니다. 거기에서 잘못되었습니다.


https://drive.google.com/file/d/1KzkMXpxL_rsBOAuBHyzqd3B7tYpnm1U_/view
I made a video of the error making process

https://postimg.cc/gallery/MBwDRPr
Printed error message

**Comment by Symbiomatrix** [comment]
Okay, pretty sure I got it - when batch count > 1 and latent mode is on, process_batch will be called once for every count; this will cause orig_lora_whatever to be overridden by the current lora.lora_forward, meaning the modded function - the actual original lora function is lost to all future generations, thus any non region gen bugging out.

I'll fix that and see if it works.

**Comment by freebag668** [comment]
> Okay, pretty sure I got it - when batch count > 1 and latent mode is on, process_batch will be called once for every count; this will cause orig_lora_whatever to be overridden by the current lora.lora_forward, meaning the modded function - the actual original lora function is lost to all future generations, thus any non region gen bugging out.
> 
> I'll fix that and see if it works.
> 
> Edit: I'm not getting any errors in a simple case of count = 2, a short prompt and switching 2 loras to another one, but it's definitely overriding the orig value which is bad and has potential for . I'll send a PR for it. Might still be a side effect of going through changethedevice multiple times, not sure how to trigger that segment (suspect it might only get there once I upgrade to the latest lora handling change).



Thank you for the test
I'm using extensions really well

**Comment by freebag668** [comment]
Normal operation confirmed
Thank you so much.

**Comment by Symbiomatrix** [comment]
Fantastic, thanks for letting me know. Couldn't really test it thoroughly so wasn't sure it didn't break something.
