### ISSUE TITLE
Lora_namer

### ISSUE THREAD

**Issue by Symbiomatrix** [hako-mikan/sd-webui-regional-prompter#33]
`self = lora_namer(self,p)`
This line seems to set self to none always, because lora_namer doesn't return a value. Is this intended?

**Comment by hako-mikan** [comment]
I was going to set LoRAs info to self, but changed to use regioner.
So that assignment is meaningless any longer and misleading.
`lora_namer(self,p)`
is better.

**Comment by Symbiomatrix** [comment]
Alright, gotcha, thanks.
