### ISSUE TITLE
I want to call it via API

### ISSUE THREAD

**Issue by ShenxingkeMjc** [hako-mikan/sd-webui-regional-prompter#330]
I really like your work. It's brilliant. I want to call via API, but I can't find the API service provider that provides this plug-in, can you recommend one for me?Thanks.

**Comment by coffeegrind123** [comment]
Like
```
{
  "prompt": "Stuff BREAK\nThings, Something BREAK\nTest",
  "alwayson_scripts": {
    "Regional Prompter": {
      "args": [
        {
          "active": true
        }
      ]
    }
  }
}
```

**Comment by metter** [comment]
Can I set the settings in the request too?

Active : On
Use base prompt : Off
Divide mode : Vertical
Divide Ratio : 1,1,1
Base Ratio : ...

**Comment by hako-mikan** [comment]
https://github.com/hako-mikan/sd-webui-regional-prompter#how-to-use-via-api

**Comment by ShenxingkeMjc** [comment]
> Like this
> 
> ```
> {
>   "prompt": "Stuff BREAK\nThings, Something BREAK\nTest",
>   "alwayson_scripts": {
>     "Regional Prompter": {
>       "args": [
>         {
>           "active": true
>         }
>       ]
>     }
>   }
> }
> ```
