### ISSUE TITLE
Can it be used with Composable Lora? 

### ISSUE THREAD

**Issue by iconnoci** [hako-mikan/sd-webui-regional-prompter#34]
Can it be used with Composable Lora? Supports different lora styles for each block
它可以支持Composable Lora吗？支持在每个不同块中应用不同lora风格。

**Comment by Symbiomatrix** [comment]
I believe that is what latent mode is intended for. Does it not suit your purposes?

https://github.com/hako-mikan/sd-webui-regional-prompter/blob/main/README.JP.md#latent

**Comment by hako-mikan** [comment]
They speaks Chinese so English is better.

https://github.com/hako-mikan/sd-webui-regional-prompter/blob/main/README.md#latent

**Comment by iconnoci** [comment]
thanks

**Comment by iconnoci** [comment]
It is expected that it can support the use of different lora in each block without Composable Lora
期待它可以不用Composable Lora，就可以支持在各个块中使用不用的lora
