### ISSUE TITLE
Doesn't works with controlnet

### ISSUE THREAD

**Issue by alexfredo** [hako-mikan/sd-webui-regional-prompter#36]
Hi when I use text2img without controlnet it's works fine, but when I enable controlnet with openpose it's doesn't works, please help !

**Comment by hako-mikan** [comment]
Is it only when this script is enabled that Openpose does not work?
It works fine in my environment, so it may be a matter of your usage conditions. 
Are there any errors in command prompt?

**Comment by Symbiomatrix** [comment]
Hello. Please share settings used, and what exactly isn't working. As shown in another issue, it should function even with multi openposes (preferably with ADD syntax). Most common problem is an older version of webui.

https://github.com/hako-mikan/sd-webui-regional-prompter/issues/23#issuecomment-1493483632

**Comment by alexfredo** [comment]
Yes the script doesn't work only when openpose is enabled, it's work perfectly when it's disabled, I don't have error message 
![settings1](https://user-images.githubusercontent.com/24534698/230370668-3c53ce0a-aede-4889-a35b-a43174d2277f.PNG)
![settings2](https://user-images.githubusercontent.com/24534698/230370690-54caa169-8184-4846-a7ff-eb79a1d5d6ff.PNG)

**Comment by alexfredo** [comment]
Openpose disabled it's perfectly okay : 
![rightcolor](https://user-images.githubusercontent.com/24534698/230371905-dbe9cd40-584c-477f-ae79-da75d2372d61.PNG)

**Comment by alexfredo** [comment]
I have the last version of automatic1111

**Comment by alexfredo** [comment]
In controlnet settings I have enabled "Allow other script to control this extension" but it's change nothing.

**Comment by hako-mikan** [comment]
When openpose dose not work, are there any errors in command prompt?

**Comment by alexfredo** [comment]
I don't have a error message no

**Comment by alexfredo** [comment]
If I put the openpose weight to 0,5 it's works, but I don't have the pose anymore

**Comment by alexfredo** [comment]
I have added a BREAK in front of the last color prompt and four "1,1,1,1" in the divide ratio now it's works :)

**Comment by alexfredo** [comment]
For example : 
Doesn't work :
green hair twintail BREAK

red blouse BREAK

orange skirt 

1,1,1

Works great :
green hair twintail BREAK

red blouse BREAK

orange skirt BREAK

1,1,1,1

**Comment by hako-mikan** [comment]
Thanks detailed info.
I'll try to figure out the cause.

**Comment by Symbiomatrix** [comment]
And if the last clause is duplicated instead of empty, it works perfectly with 1,1,1,1.5:
![BugRegionposeB](https://user-images.githubusercontent.com/41131377/230411795-7e18d114-f268-4ed4-a5df-f4765c22f87a.png)

**Comment by Kanareika** [comment]
I assume it is the same issue. When using ControlNet (openpose) and set Divide Ratio to "non-standard", such as "1, 2, 1", the regions seem to get mixed up, which makes the result not come out as expected. Here is example of "broken" generation: 
![05602-1439568092-extremely detailed digital art of a tall beautiful girl standing, ginger ponytail, detailed beautiful face and eyes, wearing a n](https://user-images.githubusercontent.com/10144329/231333438-80d4f1a5-8bc6-48e9-9840-cb9c1a6de946.png)
Image went through Hires.Fix, but original 360x640 looks just as broken.

OpenPose image is generic three skeletons:
![pose_2023_04_11_18_22_23](https://user-images.githubusercontent.com/10144329/231333755-ecd1ee51-e781-4782-bbf0-ba6a2d0537df.png)


Here is parameters:
extremely detailed digital art of a tall beautiful girl standing, ginger ponytail, detailed beautiful face and eyes, wearing a noble dress, looking at viewer, fantasy, planet background ADDCOL
extremely detailed digital art of a tall man standing, short white hair, detailed face and eyes, wearing a dark wizard robe, looking at viewer, fantasy, galaxy background ADDCOL
extremely detailed digital art of a tall beautiful girl standing, black braid, detailed beautiful face and eyes, wearing a sorcerer bodysuit, looking at viewer, fantasy, sun background
Negative prompt: (3d:1.2), worst quality, low quality, jpeg artifacts, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, mutation, bad anatomy, bad proportions, extra limbs, malformed limbs, fused fingers, too many fingers, long neck, (big breasts, huge breasts:1.3)
Steps: 16, Sampler: UniPC, CFG scale: 7, Seed: 1439568092, Size: 360x640, Model hash: f427dd7a4f, Model: theAllysMixIII_v10, Denoising strength: 0.7, ENSD: 31337, ControlNet-0 Enabled: True, ControlNet-0 Module: none, ControlNet-0 Model: difference_controlSd15Openpose [1723948e], ControlNet-0 Weight: 1, ControlNet-0 Guidance Start: 0, ControlNet-0 Guidance End: 1, RP Active: True, RP Divide mode: Horizontal, RP Calc Mode: Attention, RP Ratios: "1,2,1", RP Base Ratios: 0.2, RP Use Base: False, RP Use Common: False, RP Use Ncommon: False, RP Change AND: False, Hires upscale: 2, Hires upscaler: Latent

Changing the Sampling Method does not change anything.

**Comment by Symbiomatrix** [comment]
@Kanareika Nope, different issue. ADDCOL is 2d syntax, so for the setting you picked, it expects the ratio "1,1,2,1" in horizontal mode, or "1;1,2;1,1;1" in vertical mode (or >6 comma separated values) - see the readme section.
Since these were not supplied, it will take the first 1 to be the row height (though it makes no difference since there's only one row), the 2,1 will be used for the 1st & 2nd column, then for the remainder 3rd column it'll repeat the last value in the series, 1 - hence a 2:1:1 split.

Should probably change the visualiser to use the split method. I've tried to make the propagation fill out the gap as intuitively as possible, but the extra value even in a simulated 1d is necessary to keep the rules clear cut.

**Comment by Symbiomatrix** [comment]
I submitted a PR that should make this more intuitive, and your use case to function as expected.

**Comment by Jonseed** [comment]
I am also having this problem. If I have a ControlNet active, then the Regional Prompting doesn't work. I tried the tricks noted above without success. If I disable the ControlNet, then Regional Prompting starts working again.

**Comment by Jonseed** [comment]
I think it may have to do with multiple ControlNets active. If I only have one active (openpose) then it works. If I have openpose and reference active, then it doesn't seem to work.
