### ISSUE TITLE
Alternate form of division.

### ISSUE THREAD

**Issue by Symbiomatrix** [hako-mikan/sd-webui-regional-prompter#37]
I've just realised, we could specify in the division ratios the precise number of pixels, eg "300,150,62" split. Naturally, this isn't some special feature, but it might be worth mentioning in the readme when a high level of accuracy is wanted.

**Comment by hako-mikan** [comment]
That is correct. 
We should also add that it is better to set a divisible value.

**Comment by hako-mikan** [comment]
That's right.
We should also add that it is better to set a divisible value.

**Comment by Symbiomatrix** [comment]
Very well, I'll see if I can slip that in later.
