### ISSUE TITLE
Wrong image displayed when generating preview

### ISSUE THREAD

**Issue by Sakura-Luna** [hako-mikan/sd-webui-regional-prompter#41]
When generating images with a batch size greater than 1 in Latent mode, the preview of the generation process displays the repeated first preview instead of the preview of the corresponding sequential image.

**Comment by hako-mikan** [comment]
This is a specification and difficult to improve. This process is necessary to generate separate regions.

**Comment by Sakura-Luna** [comment]
@hako-mikan I'm not sure what you mean, are you saying that the preview is unlikely to get the content of the 2nd, 3rd... image?

![image](https://user-images.githubusercontent.com/53183413/230702958-191045f8-0513-4c9a-bae9-80efbcb7def9.png)

**Comment by Symbiomatrix** [comment]
@Sakura-Luna Has this begun to occur only on a recent commit? What happens when the processing finishes, does it suddenly jump to a different final image?
I don't think the extension touches the preview generation directly, just the forwards.

**Comment by Sakura-Luna** [comment]
@Symbiomatrix 
> Has this begun to occur only on a recent commit? 

As far as I know this issue has been around since Latent mode was added, it also affects the webui under gradio 3.16.

> What happens when the processing finishes, does it suddenly jump to a different final image? 

That's right, it only affects the preview of the process, it will look a little different in the first few steps, and then it will be exactly the same.

> Are you using one of the vanilla samplers?

This question is invalid because until now samplers like DDIM don't support Latent mode (error: composition via AND is not supported for DDIM/PLMS samplers).

**Comment by Symbiomatrix** [comment]
> it also affects the webui under gradio 3.16.
Not sure I understood that statement - you mean that you're running 3.16 and it happens elsewhere, or that the same occurs in regional with versions <3.16?

**Comment by Sakura-Luna** [comment]
> Not sure I understood that statement - you mean that you're running 3.16 and it happens elsewhere, or that the same occurs in regional latent with versions <3.16?

WebUI was recently migrated to Gradio 3.23, introducing some incompatible changes, I mean this problem exists in both 3.16 and 3.23.

**Comment by Symbiomatrix** [comment]
Oh, I see.
It would appear to be a general webui bug with the AND keyword (or image selection for preview).
Goes like this:
- sd_samplers_common.samples_to_image_grid shows stored_latent images.
- Store_latent is created by sd_samplers_kdiffusion.forward, through the call store_latent - depending on settings, it basically takes the first {batchsize} images, or the last from x_out.
- However, when there are AND keywords (which regional uses behind the scenes), sequential identical copies are created for each image, and so the first ones contain a duplicate.

The preview may receive many combinations, so I've no idea what would be the proper fix for it.
I see two simple workarounds:
- Set live preview to negative prompt, which for some reason is always singular, despite ANDs.
- Change "sd_samplers_common.store_latent(x_out[0:uncond.shape[0]])" to "sd_samplers_common.store_latent(x_out)", showing all duplicate images (not really recommended except for testing, slows the display). Example below.

In my old early feb version, I had not encountered this phenomenon, but then there were more severe problems with latent regional. Haven't tried a simple AND though, might be worth a look.

![BugRegionPreview2](https://user-images.githubusercontent.com/41131377/230749105-152c70f0-eadb-4b18-b66c-4eea16bb3435.png)

**Comment by Sakura-Luna** [comment]
@Symbiomatrix Based on your example, it seems like an easy fix.

**Comment by Sakura-Luna** [comment]
@Symbiomatrix I made a [pr](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9491) to fix this.

**Comment by Symbiomatrix** [comment]
Cheers. I hope that example is indeed representative. Though I guess since it's limited to the preview feature it's not that critical.

**Comment by Sakura-Luna** [comment]
Since it can be easily repaired, there is no need to keep it. WebUI is a relatively mature project, and the repair of details is not obtrusive.

**Comment by hako-mikan** [comment]
Thanks. I seem to have misunderstood something.
