### ISSUE TITLE
Two references

### ISSUE THREAD

**Issue by cyber-meow** [hako-mikan/sd-webui-regional-prompter#44]
Hi, great work. I would just like to suggest two potential references that can be relevant to your approach. Since I do not find other way to communicate so I decide to open an issue here.
1. [TRAINING-FREE STRUCTURED DIFFUSION GUIDANCE FOR COMPOSITIONAL TEXT-TO-IMAGE SYNTHESIS](https://arxiv.org/abs/2212.05032): This seems to be very close to the method you consider here
2. [Attend-and-Excite: Attention-Based Semantic Guidance for Text-to-Image Diffusion Models](https://arxiv.org/abs/2301.13826): This may be a little farther but it could still be of interest

**Comment by hako-mikan** [comment]
Thanks for letting me know!
Both papers are very interesting. 
I have been trying to figure out how to separate the effect of prompts for a long time.

**Comment by Symbiomatrix** [comment]
Naive question, do these methods align with loras? Frankly, that seems to me the biggest drawback for attention, rather than the measure of accuracy.

**Comment by cyber-meow** [comment]
Lora is nothing different from usual model so in principle yes. It should mostly be a problem of implementation.

**Comment by Symbiomatrix** [comment]
@hako-mikan Have you had a chance to take a look at these papers? Do they show promise compared to latent / attention, in theory?
