### ISSUE TITLE
Running 2D region assignment gives an error.

### ISSUE THREAD

**Issue by toyxyz** [hako-mikan/sd-webui-regional-prompter#46]
Running 2D region assignment gives an error. I used the settings in the description as is.

`Error running process: C:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py2<00:00, 10.68it/s]
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "C:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 526, in process
    bratios2 = split_l2(bratios, DELIMROW, DELIMCOL, fmap = ffloat, basestruct = lbreaks)
  File "C:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 138, in split_l2
    row2 = [fmap(x) for x in row2]
  File "C:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 138, in <listcomp>
    row2 = [fmap(x) for x in row2]
  File "C:\stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 70, in <lambda>
    ffloat = lambda x: float(x)
ValueError: could not convert string to float: ''`

![image](https://user-images.githubusercontent.com/8006000/230761188-2e928046-7c49-41d1-b47c-ff4b5a7d56b1.png)
![image](https://user-images.githubusercontent.com/8006000/230761194-3b7f7a14-26ef-4f2d-9f61-a1c2ba841236.png)

**Comment by Symbiomatrix** [comment]
On it!

**Comment by Sakura-Luna** [comment]
@Symbiomatrix An empty base value does not cause an error, so no modification is required.

**Comment by toyxyz** [comment]
> On it!
> 
> Edit: Can't have an empty base ratio, either in 2D or regular regions, even if it's unused. I'll add a default value, but you should put some number there for now.

Thanks! The error disappeared when I entered a number in Base ratio.

**Comment by Sakura-Luna** [comment]
There is no error here even if I add space to the base value?

**Comment by Symbiomatrix** [comment]
@Sakura-Luna
`bratios2 = split_l2(bratios, DELIMROW, DELIMCOL, fmap = ffloat, basestruct = lbreaks, indflip = indflip)`
will basically try to convert the split base to float, but with a non numerical value (eg '') this raises the error shown. I don't really see a way it could work unless float's behaviour is different for you somehow.
Unless you've happened to use BREAK instead of 2d syntax?

**Comment by Sakura-Luna** [comment]
@Symbiomatrix Exactly the same parameters, you can see the information added by the extension.

![image](https://user-images.githubusercontent.com/53183413/230773298-7e39ce07-1abe-4b4e-acb1-2d1bba9a3a95.png)

**Comment by Symbiomatrix** [comment]
Well, I guess the semicolon should've triggered 2d mode regardless of the prompt, so that should have sufficed. Can you add a print(bratios2) after the line I mentioned (two places) and tell me what it shows?
And if you use an explicit nonnumber (eg base="a"), does it err then?

**Comment by Sakura-Luna** [comment]
> And if you use an explicit nonnumber (eg base="a"), does it err then?

Either space or 'a' throws an error, but doesn't block generate, which is kind of weird, I don't have the impression of seeing any errors before downgrading the extension.

**Comment by Symbiomatrix** [comment]
@Sakura-Luna Not sure I understand what you're saying exactly, but if I recall correctly, if the extension fails to catch an exception during process before it gets to overriding the forward methods, then generation will proceed as normal, without the extension. Most likely, there's an exception catch & print in the script callback module or something (in case an extension is acting up), but I haven't investigated that part of the code thoroughly.

**Comment by Sakura-Luna** [comment]
It's ok, it's not a big deal.
