### ISSUE TITLE
resolution

### ISSUE THREAD

**Issue by TongfanWeitf** [hako-mikan/sd-webui-regional-prompter#52]
I can only use this when size is 512*512, is that a bug or a figure?

**Comment by Sakura-Luna** [comment]
Your description is too simple. If you use a larger size, what problems will you encounter? It is best to post the WebUI log.

**Comment by TongfanWeitf** [comment]
sorry for the misleading, it seems to be my mistake. It is fine to use other resolution

**Comment by hako-mikan** [comment]
Depending on the resolution and number of divisions, this may result in an error. This often happens when the resolution divided by the number of divisions is not divisible.

**Comment by Symbiomatrix** [comment]
@TongfanWeitf Are you using BREAK syntax or ADDROW/COL syntax?

**Comment by TongfanWeitf** [comment]
> Depending on the resolution and number of divisions, this may result in an error. This often happens when the resolution divided by the number of divisions is not divisible.

thank you, that make sense to me.

**Comment by TongfanWeitf** [comment]
> @TongfanWeitf Are you using BREAK syntax or ADDROW/COL syntax?

the error happens on both syntax

**Comment by Symbiomatrix** [comment]
> > @TongfanWeitf Are you using BREAK syntax or ADDROW/COL syntax?
> 
> the error happens on both syntax

Can you post a screenshot of the webui interface for each of them, with whichever prompt + dimensions + split is causing the error?

Make sure you're on the extension's latest version.
