### ISSUE TITLE
Best way to use LORAs?

### ISSUE THREAD

**Issue by dragonpam** [hako-mikan/sd-webui-regional-prompter#58]
Is there better advice on how to use LORAs in different scenarios?  There's two scenarios I'm running into:

1. A LORA that applies to the whole composition (i.e. a contrast LORA) - using as base is inconsistent, using in all rows/col over saturates, using common with base produces strange results
2. Using a subject LORA (e.g. a consistent character or post) - do you use the lora in each prompt?  what's the trade off between attention vs. latent.

thank you

**Comment by Symbiomatrix** [comment]
Hello.
To answer succinctly:
- There shouldn't theoretically be any particular issue with common + base together, as long as you place them in the correct order. Common just copypastas the clause to all regions, base acts like denoising strength combining with the region's weights. If you have a specific example to demonstrate what you mean, might be able to explain more clearly.
- Attention has the best region separation, but cannot separate loras other than through their keywords, if they have any.
- Latent loras need tweaking with the additional settings, and variations in the output are to be expected.
- In latent mode, lora's location matters - add it to the region / base according to where you want the subject to appear; if whole image, then base is definitely better than at every region (or better yet, attention). It still has some very glaring issues, particularly in high weights and certain loras more than others. We're looking for solutions or workarounds for them.
