### ISSUE TITLE
Some zone not generated

### ISSUE THREAD

**Issue by thibaudart** [hako-mikan/sd-webui-regional-prompter#59]
I try a simple 1,1,1

With 

a beautiful woman  ADDCOL 
door ADDCOL 
golden retriever

And 80% of the time, I miss one zone, for example

![image](https://user-images.githubusercontent.com/103603084/232618037-d798e05f-384e-4aa1-9eb8-79aad7abcd20.png)

**Comment by Symbiomatrix** [comment]
That's a fairly high width value. You need hiresfix for that.
