### ISSUE TITLE
Possible Enhancement: Allow subdivisions of sections with different horizontal/vertical splitting

### ISSUE THREAD

**Issue by bombasticmori** [hako-mikan/sd-webui-regional-prompter#64]
Hello. I understand this might be a bit of a vague or difficult ask, but I'll try to explain.  I've had the idea of trying to do some European Renaissance painting style gens, and one common thing they would often do is incorporate the Golden Ration into the composition of their pieces.  An example for reference would this: ![Fibonacci_Spiral svg](https://user-images.githubusercontent.com/103213389/233871443-dfe579da-ff9c-4035-a7bb-679fe155562b.png)

While an actual golden ration type setup may not be possible, I was hoping to approximate it by setting up divisions something like what you see in that image.  However it doesn't look like the way the program is set up is made for something like that, where you have ~half the image as one horizontal column and the second column as multiple vertical rows.  Do you know if it would be possible to implement something like this? If its a ton of work its not a big deal, I'm just curious.

**Comment by Symbiomatrix** [comment]
Hello.
You can get these dimensions in the current version by adding the splits marked in red:
![RegionGoldenB](https://user-images.githubusercontent.com/41131377/233962118-4f36ecc7-c600-4732-95b1-9e0be8bafa93.png)
Any single colour region split by a red line, should be given the same prompt in every subregion (copypasta). This ought to have the same effect as using a single region with said prompt (save for loras with a nonzero text encoder / unet weight, which is an open issue currently).

I don't think it would be very effective to introduce function based ratios, and a pain to parse. One way that could work though, is parenthesis in ratios, meaning something like:
`21 , (13 ; (3, (2;1,1); 5), 8)`
This would likely require an overhaul of how the ratios are interpreted; I can't perfectly grasp how the 2d interpretation would work (possibly make the outer values local to the parenthesis); we can't use parenthesis for this purpose in prompts (though I think it would be preferable to have ratios anchor the regions in this case anyway); and logically the user would have to specify the regions inside out (though this might be optional, taking the prompts left to right and fitting them to the correct order is a simple matter of rearrangement).
Overall, this is one possibility, but it's more like something you'd give as a trick question than an effective solution.

I think that if we can get the other idea, of region drawing / upload, to work in rp, then it would be a far more intuitive solution both for the user and to implement.
https://github.com/Symbiomatrix/gradio-test-polygon

**Comment by Symbiomatrix** [comment]
@bombasticmori You're now welcome to test #66 .
I haven't finished mask saving or proper upload yet, but it's possible to draw said ratios, or create & upload a mask with the colours hsv(X,0.5,0.5) then 'tag' them in LCOLOUR.

**Comment by Symbiomatrix** [comment]
Sure. Let me know if it works correctly. From my observations, seems that it's more difficult to control than matrix has been. It might be the model's limitation though, rather than the irregular edge, but there are better judges than I for this.
