### ISSUE TITLE
LoRA only functions on first generation

### ISSUE THREAD

**Issue by catboxanon** [hako-mikan/sd-webui-regional-prompter#70]
Note: I was testing this with the `ver7` branch.

Launching the web UI, with the only extension installed being this one, I can only use a LoRA the first time it's entered in a prompt, regardless if this extension is enabled or not (within the accordion). In order to use it again, I have to remove the LoRA from the prompt, generate an image, add it back, and generate again. After attempting to generate another image after this, the issue occurs again, and I must repeat this process.

Console doesn't seem to output any errors. It recognizes the LoRA in the prompt and will print the name(s) to the console, but it does this regardless if the LoRA is actually affecting the output or not.

The only optimization flag I'm using is `--opt-sdp-no-mem-attention`, I believe everything else is standard.

**Comment by Symbiomatrix** [comment]
Does this happen with attention, latent or both? I assume you've never had this problem before in main with said flag? And you're using the latest webui?
Sounds like something might be up with the regioner / weight applying in latent. I don't have the latest version so probably can't test it correctly.

**Comment by hako-mikan** [comment]
I found cause and fixing now. thanks reporting

**Comment by hako-mikan** [comment]
Fixed.

**Comment by Symbiomatrix** [comment]
@catboxanon Comments? Seems to be working on my end.
