### ISSUE TITLE
Upscaler Runtime Error

### ISSUE THREAD

**Issue by rain314159** [hako-mikan/sd-webui-regional-prompter#71]
Runtime errors occur when using the upscaler. Do you happen to know the reason for this phenomenon?
The size is a multiple of 8, and the resized size is a multiple of 8. However, runtime errors still occur.
However, if you do not use the upscalers, there will be no errors
Is this extension not compatible with the upscaler originally?

**Comment by Symbiomatrix** [comment]
Upscalers have been tested in the past, personally I've never encountered a runtime error related to them (or in general), though there has been such a report with wildcards.
Are you running the most recent vanilla webui with an nvidia card or something else?
How frequent are these runtime errors? Can you share the full settings (extension's, prompt and everything else)?

**Comment by lbeltrame** [comment]
I believe I've seen this too. It occurs when the upscaled dimensions (e.g. after hires fix) aren't a multiple of **64**.

**Comment by Symbiomatrix** [comment]
Thanks luca, I'll have a look later.

**Comment by hako-mikan** [comment]
It seemed that an error occurred if the upscaled size was not a multiple of 8, which has been corrected.

**Comment by Akikazehub** [comment]
I also encountered the same issue, as the Regional Prompter cannot use any Upscaler that works in a Tiled mode when activated.
The Tiled Diffusion and Ultimate SD upscale I tested are not working properly.
I tested scaling from 1024x1024 to 1280x1280, with dimensions both in multiples of 8 and 64.

**Comment by Akikazehub** [comment]
Note that error occurred when I was using 2D regions and Attention mode.

**Comment by hako-mikan** [comment]
I see that those upscalers divide the image into smaller areas and upscale them, but if the divided areas are too small, they cannot be handled.
