### ISSUE TITLE
a strange result

### ISSUE THREAD

**Issue by rain314159** [hako-mikan/sd-webui-regional-prompter#72]
Divide Ratio is written correctly. The picture I wanted was a picture with five men. Could you tell me if I did something wrong?
model: wintermoonmix_A.safetensors [01b259805e], vae: orangemix.vae.pt
 
good prompt
(minecraft:1.5), (five man:1.9), ((masterpiece:1.5)), ((best quality:1.5)),  <lora:gachaSplashLORA_v40:0.3>, ADDCOMM
background, ADDCOL
background, ADDCOL
background, ADDCOL
background, ADDCOL
background, ADDROW
man face, (purple eyes:1.5), (blue hood:1.5), (brown hair:1.5), perfect_face, looking_away, (detailed face:1.2), smile, (((short hair))), looking_afar, (high angle shot:1.7), ((headphones)), ADDCOL
man face, (purple eyes:1.5), (blue hood:1.5), (brown hair:1.5), perfect_face, looking_away, (detailed face:1.2), smile, (((short hair))), looking_afar, (high angle shot:1.7), ((headphones)), ADDCOL
man face, (purple eyes:1.5), (blue hood:1.5), (brown hair:1.5), perfect_face, looking_away, (detailed face:1.2), smile, (((short hair))), looking_afar, (high angle shot:1.7), ((headphones)), ADDCOL
man face, (purple eyes:1.5), (blue hood:1.5), (brown hair:1.5), perfect_face, looking_away, (detailed face:1.2), smile, (((short hair))), looking_afar, (high angle shot:1.7), ((headphones)), ADDCOL
man face, (purple eyes:1.5), (blue hood:1.5), (brown hair:1.5), perfect_face, looking_away, (detailed face:1.2), smile, (((short hair))), looking_afar, (high angle shot:1.7), ((headphones)), ADDROW
man body,long pants,(blue hood:1.5), (belt:1.1), (white lab coat:1.5),((skyblue lab gloves:1.3)), (perfect_hands, perfect_body, perfect_anatomy), indigo pants, (belt:1.1), (blue hood:1.5), ADDCOL
man body,long pants,(blue hood:1.5), (belt:1.1), (white lab coat:1.5),((skyblue lab gloves:1.3)), (perfect_hands, perfect_body, perfect_anatomy), indigo pants, (belt:1.1), (blue hood:1.5), ADDCOL 
man body,long pants,(blue hood:1.5), (belt:1.1), (white lab coat:1.5),((skyblue lab gloves:1.3)), (perfect_hands, perfect_body, perfect_anatomy), indigo pants, (belt:1.1), (blue hood:1.5), ADDCOL
man body,long pants,(blue hood:1.5), (belt:1.1), (white lab coat:1.5),((skyblue lab gloves:1.3)), (perfect_hands, perfect_body, perfect_anatomy), indigo pants, (belt:1.1), (blue hood:1.5), ADDCOL
man body,long pants,(blue hood:1.5), (belt:1.1), (white lab coat:1.5),((skyblue lab gloves:1.3)), (perfect_hands, perfect_body, perfect_anatomy), indigo pants, (belt:1.1), (blue hood:1.5)

bad prompt
lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name, nsfw, ng_deepnegative_v1_75t, (woman:2), (Appearance from behind:1.5), (short pants:1.9),(Stockings:1.8), (long hair:1.5), (logo:1.9), (girl:2), (breast:1.9),  ADDCOMM

This is the result
![00157-4141658627-(minecraft_1 5), (five man_1 9), ((masterpiece_1 5)), ((best quality_1 5)),  _lora_gachaSplashLORA_v40_0 3_, ADDCOMM_background,](https://user-images.githubusercontent.com/131674715/235280706-77a0a14c-9fe4-475a-a52f-45c583842b53.png)

**Comment by Symbiomatrix** [comment]
What's the divide ratio, attention / latent, horizontal / vertical, cfg, steps, unet / textual weight?
If possible, send all the gen settings, but I think the above should suffice.
I'm not quite familiar with moonmix, but these seem like rather extreme weights compared to what I use normally. There's also an issue with latent mode where certain loras cause corruptions in regions which don't have the lora (depending on unet / text), and a high cfg value could cause divergence (doesn't really look like the type I know however).
