### ISSUE TITLE
Output breaks after a certain amount of words in prompt

### ISSUE THREAD

**Issue by matrix4767** [hako-mikan/sd-webui-regional-prompter#73]
I have noticed that once enough words are written in the positive prompt, the output starts to mess up, the bottom part of the image gets sort of blurry and scrambled.

**Comment by Symbiomatrix** [comment]
That might be caused by a bug in the context separation (the threshold is 75 tokens / 'words'), I suspected something but nobody had brought it up.
Can you share examples of before & after where you get this blurriness?

**Comment by matrix4767** [comment]
I think it's caused by the 2d region mode, as I used ADDROW to divide the regions instead of BREAK. With BREAK, the output was fine. Version is current main version that is updated through the webui.

**Comment by Symbiomatrix** [comment]
Well, the bug I have in mind is when you combine BREAK with ADDROW; I think it skips the region.
If it's something else, I'll need the specific settings, I can't see anything going obviously wrong with just row & common.

**Comment by matrix4767** [comment]
No, I didn't use both BREAK and ADDROW at once. Just enough tokens  with ADDROW. The lowest part of the output will start collapsing.

**Comment by matrix4767** [comment]
Looks like as soon as one pos goes over 75 in tokens, the output breaks. pos tokens : [59, 74, 63] was fine, pos tokens : [59, 89, 63] was not. Whether it's ADDROW/ADDCOL or BREAK used in the prompt.

**Comment by hako-mikan** [comment]
I tested pos [61, 87, 59], neg tokens : [8] and worked well.
Could you tell me your settings.
Using loras or not, or other extensions etc.
