### ISSUE TITLE
Error when using img2img

### ISSUE THREAD

**Issue by DiceOwl** [hako-mikan/sd-webui-regional-prompter#8]
First, thanks for the extension, I find it useful.

Now for the bug, when using img2img, the extension errors out with the following message.

stable-diffusion-webui\extensions\sd-webui-regional-prompter\scripts\rp.py", line 110, in process
    self.hr = p.enable_hr
AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'enable_hr'

It looks to me like the hires. setting, replacing the line with self.hr = getattr(p,'enable_hr',False) is good enough?

**Comment by Symbiomatrix** [comment]
Good point. Since other hr attributes don't exist either, you might as well:
```
            if hasattr(p,"enable_hr"):
                self.hr = p.enable_hr
                self.hr_w = (p.hr_resize_x if p.hr_resize_x > p.width else p.width * p.hr_scale)
                self.hr_h = (p.hr_resize_y if p.hr_resize_y > p.height else p.height * p.hr_scale)
```
Other than that, sure - it's just for changing the dimensions.
Img2img seems to function correctly, but I'm getting discolouration issues at high str. Might be unrelated.

**Comment by hako-mikan** [comment]
fixed
