### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [hako-mikan/sd-webui-regional-prompter#83]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the AGPL-3.0-or-later license to match the upstream project and so that others are encouraged to contribute changes back to your project.

**Comment by Symbiomatrix** [comment]
I was wondering when that would come up.
Personally I don't mind which, it's hako's project.

**Comment by hako-mikan** [comment]
Thanks for the advice. I have very little knowledge about licenses so I will study and then set up a license.

**Comment by TechnologyClassroom** [comment]
Since the project is an extension for a project that is AGPL, there isn't much to learn or think about. This project's license would be AGPL. You create a new file called LICENSE, and GitHub walks you through the steps. You select AGPL and save.

**Comment by hako-mikan** [comment]
thanks added
