### ISSUE TITLE
Using 2 LORA (Latent mode) Doesn't work

### ISSUE THREAD

**Issue by freebag668** [hako-mikan/sd-webui-regional-prompter#86]
c6403484 (Mon May 1 10:59:09 2023) | latest

https://civitai.com/models/6679
https://civitai.com/models/6362
Using LORA

https://anonfiles.com/Lbf1A3o1zb/20230501_txt
debug TXT ifle

https://postimg.cc/gallery/n7YbNqd
Using 2 LORA (Latent mode)
Resulting Picture

Doesn't detach from latent mode
Can this be fixed?

**Comment by hako-mikan** [comment]
Fixed.

**Comment by freebag668** [comment]
Thank you
All is well now
