### ISSUE TITLE
Vertical mode doesn't work as expected

### ISSUE THREAD

**Issue by YarivTawili** [hako-mikan/sd-webui-regional-prompter#91]
In vertical mode, I use Devide mode of "1;2,1,3;1" - shuold mean add 3 columns:
Col 1: 0.25 of the image width (1/4) and has no rows (all image height)
Col 2: 0.5 of the image width (2/4) and has two rows (1/4 and 3/4 of the image height)
Col 3: 0.25 of the image width (1/4) and has no rows (all image height)
See image (visual vs expected)

![Reg02](https://user-images.githubusercontent.com/129671729/235583001-ca3bd110-b913-4538-afcc-745cfafb25b4.jpg)

**Comment by Symbiomatrix** [comment]
Nope. That's in horizontal mode. In vertical mode, think of the commas as the outer separators: you have 1;2 | 1 | 3;1 . Therefore, two columns of 20% and one of 60%. In order to get the desired result, you'd need 1,2;1;3,1 - a perfect reversal of comma and semicolon (which is what happens behind the scenes).

**Comment by hako-mikan** [comment]
fixed

**Comment by YarivTawili** [comment]
Thanks, your explaination was clear and the visualisation looks as I wanted. 
I'll be greatful if you could help me understand what is wrong since the result I'm getting are not as expected at all.
I used this prompt, without base or common prompts but happens with Use common negative prompt = true and false, image size 768 X 549:

"standing african warrior guard ADDCOL 
Intricte jungle ADDROW 
african warrior queen, wearing a tribal outfit made of exotic animal skin, (sitting on a throne in the jungle:1.5), slender waist, slender thighs, toned muscles, ADDCOL 
standing african warrior guard"

It should be two standing male guards in the sides of a sitting african woman. All the results I'm getting are of a sitting woman, not always in the middle and always from top to buttom (the purple reactangle in the image I sent in my original message should have limited this square to 3/4 height). With debug checkbox set, this is what I see in the console:

Warning: Nonstandard height / width.
Warning: Nonstandard height / width for ulscaled size
Error running process: D:\Stable-diffusion\stable-diffusion-portable-main\extensions\sd-webui-regional-prompter\scripts\rp.py
Traceback (most recent call last):
  File "D:\Stable-diffusion\stable-diffusion-portable-main\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
  File "D:\Stable-diffusion\stable-diffusion-portable-main\extensions\sd-webui-regional-prompter\scripts\rp.py", line 244, in process
    self, p = keydealer(self, p)
  File "D:\Stable-diffusion\stable-diffusion-portable-main\extensions\sd-webui-regional-prompter\scripts\rp.py", line 623, in keydealer
    if KEYCOMM in p.negtive_prompt:
AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'negtive_prompt'

before_process_batch :  standing african warrior guard ADDCOL
Intricte jungle ADDROW
african warrior queen, wearing a revealing tribal outfit made of exotic animal skin, (sitting on a throne in the jungle:1.5), slender waist, slender thighs, toned muscles, ADDCOL
standing african warrior guard
100%|██████████████████████████████████████████| 30/30 [00:18<00:00,  1.61it/s]
postprocess_image :  0 0 standing african warrior guard ADDCOL 0:00,  1.58it/s]
Intricte jungle ADDROW
african warrior queen, wearing a revealing tribal outfit made of exotic animal skin, (sitting on a throne in the jungle:1.5), slender waist, slender thighs, toned muscles, ADDCOL
standing african warrior guard ['standing african warrior guard ADDCOL \nIntricte jungle ADDROW \nafrican warrior queen, wearing a revealing tribal outfit made of exotic animal skin, (sitting on a throne in the jungle:1.5), slender waist, slender thighs, toned muscles, ADDCOL \nstanding african warrior guard']
mode : Attention
divide : Vertical
usebase : False
base ratios : []
usecommon : False
usenegcom : True
use 2D : False
divide : 0
eq : []

Error running postprocess: D:\Stable-diffusion\stable-diffusion-portable-main\extensions\sd-webui-regional-prompter\scripts\rp.py
Traceback (most recent call last):
  File "D:\Stable-diffusion\stable-diffusion-portable-main\modules\scripts.py", line 444, in postprocess
    script.postprocess(p, processed, *script_args)
  File "D:\Stable-diffusion\stable-diffusion-portable-main\extensions\sd-webui-regional-prompter\scripts\rp.py", line 364, in postprocess
    if self.debug : debugall(self)
  File "D:\Stable-diffusion\stable-diffusion-portable-main\extensions\sd-webui-regional-prompter\scripts\rp.py", line 612, in debugall
    print(f"tokens : {self.tokens}, {self.pt}, {self.nt}\n")
AttributeError: 'Script' object has no attribute 'tokens'

Total progress: 100%|██████████████████████████| 30/30 [00:19<00:00,  1.55it/s]
Total progress: 100%|██████████████████████████| 30/30 [00:19<00:00,  1.58it/s]

Any idea?

**Comment by hako-mikan** [comment]
Your script seems to be old version. Current script not have `self.tokens`
Please update it.

**Comment by YarivTawili** [comment]
I just did and the error disapeared. BUT now my old devide mode ("1;2,1,3;1") which you said was wrong, is giving me the division I wanted (see below) while your devide mode ("1,2;1;3,1") is giving just 3 columns.
You also added ton of debug info so I can't even mark it all and paste here

![Reg03](https://user-images.githubusercontent.com/129671729/235746344-6d3ac299-eba7-4f9c-8419-3902e7cea0f9.jpg)

**Comment by Symbiomatrix** [comment]
@YarivTawili Some keyword detection code was changed because of other issues, this one was misidentified as a bug. It's been reverted and should work as intended on the latest version.

**Comment by Symbiomatrix** [comment]
@YarivTawili I believe that's where ADDCOMM / ADDBASE come in. Stable diffusion on virtually all checkpoints not trained specifically for it, dislikes multi character renderings. It will avoid those and tend to lose quality when it obliges. A central character is dandy, the jungle background's okay, but in order to get more people you'll need to ask harder.
Something like "(three african warrior women) ADDCOMM ...". How well the checkpoint obliges depends on its nature (ie how forceful you need to be without regions). The regions just make the pieces of the scene fall into place a little more accurately, they are not entirely separate gens.
