### ISSUE TITLE
bigger canvas for draw mask feature

### ISSUE THREAD

**Issue by JaysonPhoenix** [hako-mikan/sd-webui-regional-prompter#98]
[solved]
well how would i manually draw on the canvas? since the canvas has the pencil button but not the color selection button thats supposed to be below the size button. for me it looks like in the screenshots from this #94 issue thread too. 
i remember theres a launch argument or a py command or something to enable some drawing elements, never used it but remember i read something about it was removed in some update but can still be enabled that way, is this feature missing for the inpaint masking of rp to work maybe?
[edit]:
oh nevermind, how stupid, i figured it out xD after fiddling a bit more and reading the tutorial again and again i eventually drew black and clicked on draw mask without chosing a color that i was looking for.... it colors the last black mask drawn area by itself and when looking at the screenshots in the tutorial again it kinda made sense xD so sry for the issue thread here but take this as an example that the tutorial maybe needs to be a bit more clear on that, expecially in the text part which was a bit misleading for me. i'll still stick to the canvas size comment so i'll just change the title.

there really needs to be a way to enlarge the canvas somehow in order to properly draw on it, how am i supposed to draw on such a small image? ^^ maybe a button to enable a full canvas below the input image at the top of the page (like in img2img inpaint upload) or at least resize the canvas to full extension width maybe with an expand tab. god i hate how clunky automatic is for all extension stuff compared to modern uis like invoke or whatever...

**Comment by Symbiomatrix** [comment]
1) Please read the instructions. Or gloss over the small picture guide below them. The canvas works a little differently than what you may expect for specific reasons.
https://github.com/hako-mikan/sd-webui-regional-prompter#mask-regions-aka-inpaint-experimental-function
2) You are welcome to find a way to do that in gradio and submit a PR. Personally I don't really see that as high priority.

**Comment by JaysonPhoenix** [comment]
uhh that was a fast answer, faster than i could edit my post since i already figured it out ^^ but as i said it wasnt so clear to me from that tutorial text which of course makes sense now together with the pictures after i figured it out. still maybe it could be worded a tiny bit different so one doesnt get the idea when talking about drawing and colors that you actually had to draw a color on the image instead of just outlining an area in black (not even filling it, which the pics kinda show if you pay enough attention i guess, but maybe not at a first glimpse and the text maybe doesnt describe it exactly enough for guys like me, idk ^^)

for the canvas part, i have no idea how to do something like that so i can only mention it and hope for somebody finding a solution. i really like the feature but the canvas is really small so its really hard to draw there. no idea how high of a priority that is since probably theres more technically important stuff on such a great extension, but for the feature itself at least it kinda seems important to be able to draw properly when its about drawing something, like in the issue thread i mentioned where you suggested drawing if he cant do it with a photoshop mask but he thinks needed to draw kinda exactly which i thought too (i didnt test yet how much of a difference it makse since you said the areas bleed into each other anyways), so for something like that a bigger canvas would be important, but if its really that inaccurate then of course its no priority i guess. 

thx for the fast reply tho ;)

**Comment by Symbiomatrix** [comment]
I see. I'm aware my explanations can be quite verbose, but it's a different point of view for the features for the programmer than it is for the user. It'd be helpful if you could let me know what would be the right way to emphasise the automatic colour generation, without making the explanation longer still.

General precision is a priority. Better upload & preset mask saving features are currently in the final stages; however, I don't have time to finish them this week. As far as resizing goes, the best I can do is make the mask drawing area twice as big by placing it in its own column - the size of the inpaint canvas. The input-output column split in the ui comes before extensions get a say.

**Comment by Symbiomatrix** [comment]
There. Need to move to its own row, give it an elem id, and add style.css like img2img's height adjustment.

![RegionalMaskCss](https://user-images.githubusercontent.com/41131377/236714522-4bdfc516-3500-42a8-97ad-531a1d14bb0d.png)

**Comment by JaysonPhoenix** [comment]
well english is not my main language but i'll try. guess the important part is that you draw a BLACK outline or filled area and it will add the right color when pressing draw region by itself. and also maybe in general use less words like polygon or increment and stuff like that since for a programmer or something thats common language of course but maybe not for every user during a quick read to get started fast, 

maybe something like this:
"Draw a black filled area or just an outline enclosing the region desired in the canvas area. Then press draw region, which if its not filled yet will fill the area in a color according to the mask region number currently selected on the region bar."

for the canvas size part, thats great already! :) maybe its possible at some later point to find other ways but for now thats a pretty quick cool fix. idk maybe its possible use the code canvas zoom extension does, you know that one? can hold a key to "zoom" makin the canvas as big as you need it and move it around while also adding some hotkeys for brush size for example. not perfect but working around some ui limitations for kinda the same issue.

also while we're on it, maybe theres some quick way to show which color corresponds to which region number, like for example color code the number shown on the region bar. and some extensions have a function to fetch the resolution from other sources as an option, if that was on by default it would save the step of fiddeling with the resolution bars too. and maybe for the photoshop mask part the description isnt clear too, at least for me it isnt really. maybe theres an easier way to pick colors in the external tool and assign them in the ui later? no idea for the color selecting part since i have no idea what kind of colors are right from that tutorial text, but for the other part maybe something like a color picker tool to quickly pick from an uploaded mask while a region is selected or something? but anyways, thats all not as important as beeing able to properly draw on a drawing canvas, so just adding some thoughts here ;)

**Comment by Symbiomatrix** [comment]
Okay. I'll edit that section later.
I have seen canvas zoom in the past. It is a complex pure js solution, so I would likely be unable to maintain that at all, if I could even get it to work.
I ignored it the first time out of politeness, but it seems to be a pattern so I shouldn't: You must not tell people "while you're at it". If you requested a random stranger to buy you groceries while they're at it because you saw them going into the supermarket, at best they wouldn't dignify the request with a response. Recall that you are getting for free what is otherwise a very valuable commodity: a programmer's attention and time. And I'm not talking about me, I'm talking about the stable diffusion project as a whole. Do not trivialise their efforts, that is a surefire method to drive away the people who have better things to do.
I'm not a frontend developer and hako's time is better spent on larger parts of the extension's design, so whilst such features may improve the ux, I doubt they'll be addressed for the most part. Feature creep is a serious hazard and every addition (not bugfix) must be accompanied with clear justification. Thoughts are encouraged, but if you don't know the code, assume at least that the difficulty scale is (roughly speaking, also taking into account bugs & future support):
bugfix \<\< extending a feature \<\< heisenbug \<\< importing a feature from elsewhere \<\< inventing a feature,
and think also of how to bring down the difficulty. I do pretty much the same thing. For example, with masks: since gradio's colour sketch is not built for regions, rather than invent one that is, I extended the region part from the basic inpaint and number, along with some simple computer vision techniques (which a chatbot explained and I adapted).

**Comment by JaysonPhoenix** [comment]
im sorry but you must have gotten me wrong there and i hope i dont get you wrong now too... that wasnt a "hey i want this and that, and while your on it also give me 10 other things real quick" or something, why would you think that? i said "while we're on it" meaning while im here or while we are already talking about a feature i might aswell mention another idea/feedback on the same feature that just came up... 
i even only mentioned that the canvas probably should have a size one can properly draw on because thats what i stumbled upon when i actually came for my missunderstanding of the tutorial of how to draw a region thinking it might be a bug, so i mentioned it "while im already at it" to write something here and somebody else "will already be at it" to answer my tutorial question anyway.
for the rest of the conversation you asked for what could have been written better in the tutorial and provided a quick fix idea for the canvas size explaining why it cant be done better for now which i appreciated and that like i mentioned solved the problem already for now. thinking about what you said i came up with an idea that might work around the limitations you mentioned at some later point, knowing that wouldnt be such a quick implementation as your quick fix was, i of course didnt expect you to do that right now or whatever. and "while i was on it" to think about that and provide an idea and have a conversation with you i was only adding some more feedback or idea on the same feature, which i didnt expect you to work on right now either.

so i wont feel ashamed now for taking some more time then necessary after my issue was solved already to try to help and come up with an idea or adding some further feedback you might not have thought about yet while im answering anyway. your comparison to the supermarket stranger is way off aswell as making it sound like i got the pattern to demand or like im lucky you waste your valuable time on me. asking something when you dont understand something should never be wrong and mentioning an idea or a feedback shouldnt be either, and who spends his time on answering or doing something at whatever point in time is up to each their own. 

having said that i'll stick with i keep believing you just got me wrong and this is just a misunderstanding and maybe i got you on the wrong foot at that time or on a sensetive topic in general of people demanding stuff from you while you dont have enough time to deal with every little thing or something. i appreciate you answering so fast that i couldnt even edit my original post fast enough and then even coming up with a direct quick fix i didnt expect you to at all. and im aware of coding stuff can be complex and takes time and you guys probably have other priorities to work on. but you probably also want to create something good so youd want to know how it turns out for the user aswell, so while i appreciate you coding you hopefully also appreciate your users to provide feedback, which isnt always somebody demanding to get something from you right now ;)

so i didnt intend to demand anything and you didnt intend to talk top down making me feel bad and we're good, right? ;)
